import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {bindSceneExport} from './advancedVisualExport.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {createDynamics,dynamicsStats,setDynamicsTemperature,stepDynamics} from './advancedDynamicsModel.js';
import './advancedChartExperiment.css';

export default function AdvancedDynamicsExperiment(){
  const [running,setRunning]=useState(false),[temperature,setTemperature]=useState(1),[density,setDensity]=useState(.4),[speed,setSpeed]=useState(1),[stepToken,setStepToken]=useState(0),[resetToken,setResetToken]=useState(0);
  const [stats,setStats]=useState(()=>dynamicsStats(createDynamics())),[history,setHistory]=useState([]);
  const host=useRef(null),live=useRef(null),latest=useRef({running,speed});latest.current={running,speed};
  useEffect(()=>{
    const el=host.current,renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Lennard-Jones particle simulation: drag to rotate, scroll to zoom.');el.appendChild(renderer.domElement);
    const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(8,6,9);const controls=new OrbitControls(camera,renderer.domElement);controls.minDistance=5;controls.maxDistance=25;controls.saveState();scene.add(new THREE.HemisphereLight(0xf0f8ff,0x10253a,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-3,7,5);scene.add(light);
    const spheres=new THREE.InstancedMesh(new THREE.SphereGeometry(.23,24,16),new THREE.MeshPhysicalMaterial({color:0x78c9eb,roughness:.3,metalness:.05,clearcoat:.2}),32);scene.add(spheres);
    const cube=new THREE.BoxGeometry(1,1,1),box=new THREE.LineSegments(new THREE.EdgesGeometry(cube),new THREE.LineBasicMaterial({color:0x4f8cb8}));cube.dispose();scene.add(box);
    let state=createDynamics(),frame=0,last=0,accumulator=0,lastReadout=0;
    const draw=()=>{box.scale.setScalar(state.box);const m=new THREE.Matrix4();for(let i=0;i<state.count;i++){m.makeTranslation(...[0,1,2].map(k=>state.p[3*i+k]-state.box/2));spheres.setMatrixAt(i,m);}spheres.instanceMatrix.needsUpdate=true;spheres.computeBoundingSphere();renderer.render(scene,camera);};
    const unbindExport=bindSceneExport(renderer.domElement,draw,'chemistry-dynamics.png');
    const report=()=>{const values=dynamicsStats(state);setStats(values);setHistory(old=>[...old.slice(-99),values]);};
    function tick(now){frame=0;if(!latest.current.running||document.hidden)return;accumulator+=Math.min(.05,(now-last)/1000)*latest.current.speed*.25;last=now;while(accumulator>=.002){stepDynamics(state);accumulator-=.002;}draw();if(now-lastReadout>120){report();lastReadout=now;}frame=requestAnimationFrame(tick);}
    const sync=()=>{cancelAnimationFrame(frame);frame=0;if(latest.current.running&&!document.hidden){last=performance.now();frame=requestAnimationFrame(tick);}};
    const resize=new ResizeObserver(()=>{const r=el.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix();draw();});resize.observe(el);controls.addEventListener('change',draw);document.addEventListener('visibilitychange',sync);
    live.current={sync,reset:(rho,temp)=>{state=createDynamics(rho,temp);accumulator=0;controls.reset();setHistory([]);report();draw();},heat:temp=>{setDynamicsTemperature(state,temp);report();draw();},step:()=>{for(let i=0;i<10;i++)stepDynamics(state);report();draw();}};draw();report();
    return()=>{unbindExport();cancelAnimationFrame(frame);resize.disconnect();document.removeEventListener('visibilitychange',sync);controls.dispose();spheres.geometry.dispose();spheres.material.dispose();spheres.dispose();box.geometry.dispose();box.material.dispose();renderer.dispose();el.replaceChildren();live.current=null;};
  },[]);
  useEffect(()=>{live.current?.sync();},[running]);
  useEffect(()=>{live.current?.reset(density,temperature);},[density,resetToken]);
  useEffect(()=>{live.current?.heat(temperature);},[temperature]);
  useEffect(()=>{if(stepToken)live.current?.step();},[stepToken]);
  function reset(){setRunning(false);setTemperature(1);setDensity(.4);setSpeed(1);setResetToken(t=>t+1);}
  const totalRange=Math.max(1,...history.map(v=>Math.abs(v.total/32)));
  return <section className="avc-chart-experiment" aria-label="Molecular dynamics"><header><div><h2>Molecular dynamics</h2><p>32 monatomic Lennard-Jones particles · periodic boundaries · velocity-Verlet integration</p></div><button onClick={reset}>↻ Reset dynamics</button></header><div className="avc-chart-workspace"><article><div className="avc-lattice-canvas" ref={host}/><div className="avc-chart-readouts"><output>Time: {stats.time.toFixed(3)} τ</output><output>T*: {stats.temperature.toFixed(3)}</output><output>K/N: {(stats.kinetic/32).toFixed(3)} ε</output><output>U/N: {(stats.potential/32).toFixed(3)} ε</output><output>E/N: {(stats.total/32).toFixed(3)} ε</output></div><svg viewBox="0 0 600 100" className="avc-md-trace" aria-label="Total energy per particle versus sample index"><path d="M20 10V80H580" stroke="#7d9bb3" fill="none"/><path d={history.map((v,i)=>`${i?'L':'M'}${20+i/99*560},${45-v.total/32/totalRange*30}`).join(' ')} fill="none" stroke="#55dec8" strokeWidth="2"/><text x="30" y="96">Total E/N · recent samples · vertical scale ±{totalRange.toFixed(1)} ε</text></svg></article><aside><h3>Simulation controls</h3><label>Set kinetic temperature T*<output>{temperature.toFixed(2)}</output><input aria-label="Set kinetic temperature" type="range" min=".3" max="2" step=".1" value={temperature} onChange={e=>setTemperature(+e.target.value)}/></label><label>Number density ρ* (reinitializes)<output>{density.toFixed(2)}</output><input aria-label="Number density" type="range" min=".15" max=".75" step=".05" value={density} onChange={e=>{setRunning(false);setDensity(+e.target.value);}}/></label><label>Playback speed<output>{speed.toFixed(1)}×</output><input aria-label="Dynamics speed" type="range" min=".5" max="3" step=".5" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label><button onClick={()=>setRunning(v=>!v)}>{running?'Pause dynamics':'Run dynamics'}</button><button onClick={()=>{setRunning(false);setStepToken(n=>n+1);}}>Step 0.020 τ</button><p>Changing T* rescales velocities once. Between changes, kinetic and potential energy exchange freely; no thermostat is applied. Particles crossing a boundary re-enter from the opposite side.</p></aside></div><footer><h3>Model and units</h3><p>U(r)=4ε[(σ/r)¹²−(σ/r)⁶], with a force-shifted cutoff at min(2.5σ,L/2). Units use σ=ε=m=kB=1; τ=σ√(m/ε). Deterministic FCC starting positions and zero center-of-mass velocity make Reset reproducible. This is a simple monatomic fluid, not a water or reactive-molecule model. Temperature is computed from 3(N−1) degrees of freedom.</p></footer></section>;
}
