import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, CircleDot, Database, Dna, Home, Maximize2, Play, RotateCcw, Settings2, Sparkles } from 'lucide-react';
import MolstarViewer from '../components/molecular-viewer/MolstarViewer.jsx';
import ViewerErrorBoundary from '../components/molecular-viewer/ViewerErrorBoundary.jsx';
import './biochemistryPages.css';

const topics = ['Proteins', 'Membranes', 'Carbohydrates', 'Nucleic acids', 'Metabolism'];
const topicData = {
  Proteins: { entity:'Myoglobin', subtitle:'Oxygen-binding globin fold', action:'heme pocket', metric:'Structure readiness', id:'1MBN', source:{url:'/assets/proteins/1MBN.pdb',format:'pdb',label:'1MBN sperm whale myoglobin'}, sourceType:'pdb', metadata:'X-ray · 2.0 Å · Physeter catodon', route:'bio-proteins', icon:Dna, ligand:'HEM' },
  Membranes: { entity:'Na⁺/K⁺-ATPase', subtitle:'Ion-pumping membrane transporter', action:'transport complex', metric:'Structure readiness', id:'4HQJ', source:{url:'/assets/membranes/structures/4HQJ.cif',format:'mmcif',label:'4HQJ Na,K-ATPase'}, sourceType:'mmcif', metadata:'X-ray · 4.30 Å · Sus scrofa', route:'bio-membranes', icon:CircleDot, ligand:'ADP' },
  Carbohydrates: { entity:'D-Glucose', subtitle:'Pyranose energy building block', action:'stereochemistry', metric:'Conformer readiness', id:null, source:{url:'/assets/carbohydrate-studio/structures/d-glucose.sdf',format:'sdf',label:'PubChem D-glucose conformer'}, sourceType:'sdf', metadata:'PubChem CID 5793 · experimental stereochemistry', route:'bio-carbohydrates', icon:Sparkles, small:true },
  'Nucleic acids': { entity:'B-DNA dodecamer', subtitle:'Double helix and base pairing', action:'base-pair geometry', metric:'Structure readiness', id:'1BNA', source:{url:'/assets/nucleic-acid/structures/1BNA.cif',format:'mmcif',label:'1BNA B-DNA dodecamer'}, sourceType:'mmcif', metadata:'X-ray · 1.90 Å · synthetic DNA', route:'bio-nucleic-acids', icon:Dna },
  Metabolism: { entity:'Aconitase–citrate', subtitle:'Citric-acid-cycle enzyme complex', action:'active site', metric:'Structure readiness', id:'1C96', source:{url:'/assets/biochemistry/structures/1C96.cif',format:'mmcif',label:'1C96 aconitase citrate complex'}, sourceType:'mmcif', metadata:'X-ray · 1.81 Å · Sus scrofa', route:'bio-metabolism', icon:Activity, ligand:'FLC' },
};

export default function BioVisualsTargetPage({ onNavigate }) {
  const viewerRef = useRef(null);
  const [topic, setTopic] = useState('Proteins');
  const [tab, setTab] = useState('Structure');
  const [route, setRoute] = useState(1);
  const [query, setQuery] = useState('');
  const [notice, setNotice] = useState('');
  const [style, setStyle] = useState('Cartoon');
  const [ready, setReady] = useState(false);
  const [selectedAtom, setSelectedAtom] = useState(null);
  const active = topicData[topic];
  useEffect(() => { setReady(false); setSelectedAtom(null); setStyle(active.small ? 'Ball & stick' : 'Cartoon'); }, [active]);
  const representation = useMemo(() => ({
    Cartoon: style === 'Cartoon', Surface: style === 'Surface', BallAndStick: style === 'Atoms' || style === 'Ball & stick', Spacefill: style === 'Space filling', Ligand: !active.small, Branched: !active.small, Ion: !active.small,
  }), [active.small, style]);
  const styles = active.small ? ['Ball & stick', 'Space filling'] : ['Cartoon', 'Surface', 'Atoms'];
  const filteredTopics = topics.filter(item => `${item} ${topicData[item].entity} ${topicData[item].subtitle}`.toLowerCase().includes(query.toLowerCase()));
  const announce = message => setNotice(message);
  return <div data-bio-page="overview" className="min-h-screen overflow-hidden bg-[#071522] text-slate-100" style={{fontFamily:'Inter,ui-sans-serif,system-ui'}}>
    <header className="bio-hub-header flex h-[64px] items-center gap-4 border-b border-white/10 bg-[#091b2b] px-5"><Dna size={38} className="text-cyan-300"/><div><h1 className="text-2xl font-black">Biochemistry Visual Lab</h1><p className="text-xs text-slate-400">Coordinate-backed chemistry of living systems</p></div><input value={query} onChange={e=>setQuery(e.target.value)} className="ml-auto w-[430px] rounded-full border border-white/15 bg-slate-900/60 px-4 py-2 text-xs" placeholder="Search structures, pathways, or concepts..."/>{['Explore','Learn','Simulate','Resources'].map(item=><button key={item} onClick={()=>announce(item+' selected')} className="text-xs">{item}</button>)}<Settings2 size={18}/></header>
    <div className="bio-hub-layout grid h-[calc(100vh-64px)] grid-cols-[185px_1fr_325px] grid-rows-[1fr_145px] gap-2 p-2">
      <aside className="row-span-2 flex flex-col gap-1 border-r border-white/10 bg-[#081c2d] p-3">{[[Home,'Home'],...topics.map(item=>[topicData[item].icon,item])].map(([Icon,item])=><button key={item} onClick={()=>{if(item==='Home'){onNavigate?.('dashboard');return;}setTopic(item);announce(item+' preview selected');}} className={`flex items-center gap-3 rounded px-3 py-3 text-left text-xs ${topic===item?'bg-cyan-300/15 text-cyan-200':'text-slate-300'}`}><Icon size={19}/>{item}</button>)}<div className="mt-auto border-t border-white/10 pt-4 text-xs text-slate-500">Experimental coordinates<br/>Local, repeatable previews</div></aside>
      <main className="bio-hub-main relative min-h-0 overflow-hidden rounded-lg border border-white/10 bg-[#06131f]">
        <div className="absolute inset-x-0 top-0 z-20 flex items-start justify-between gap-3 bg-gradient-to-b from-[#06131ff5] to-transparent p-4 pb-12"><div><p className="text-[10px] uppercase tracking-[.2em] text-cyan-300">Interactive molecular preview</p><h2 className="text-2xl font-black">{active.entity}</h2><p className="text-xs text-slate-300">{active.subtitle} · {active.metadata}</p></div><div className="flex flex-wrap justify-end gap-1 rounded border border-white/10 bg-[#06131fdc] p-2 text-[10px]"><span className={ready?'mr-1 self-center text-emerald-300':'mr-1 self-center text-slate-400'}>{ready?'Mol* ready':'Loading coordinates…'}</span>{styles.map(item=><button key={item} aria-pressed={style===item} onClick={()=>setStyle(item)} className={`rounded border px-2 py-1 ${style===item?'border-cyan-300 bg-cyan-300/15':'border-white/15'}`}>{item}</button>)}{active.ligand&&<button onClick={()=>viewerRef.current?.focusLigandId(active.ligand,'A')} className="rounded border border-white/15 px-2 py-1">Focus ligand</button>}<button aria-label="Reset molecular preview" onClick={()=>viewerRef.current?.reset()} className="rounded border border-white/15 p-1"><RotateCcw size={13}/></button><button aria-label="Full screen molecular preview" onClick={()=>viewerRef.current?.fullscreen()} className="rounded border border-white/15 p-1"><Maximize2 size={13}/></button></div></div>
        <ViewerErrorBoundary label={`${active.entity} preview`}><MolstarViewer ref={viewerRef} source={active.source} sourceType={active.sourceType} pdbId={active.id} label={active.entity} representation={representation} colorScheme={active.small?'element':'chain'} showLabels={false} onReady={()=>{setReady(true);requestAnimationFrame(()=>viewerRef.current?.zoom(active.small?1.45:1.18));}} onLoadError={()=>setReady(false)} onSelectionChange={setSelectedAtom}/></ViewerErrorBoundary>
        <div className="pointer-events-none absolute bottom-[92px] right-3 z-20 max-w-[65%] rounded bg-[#06131fdd] px-2 py-1 text-right text-[10px] text-slate-300">{selectedAtom?`${selectedAtom.element} · ${selectedAtom.residueName} ${selectedAtom.atom} · chain ${selectedAtom.chain} · [${selectedAtom.coordinates.map(value=>value.toFixed(2)).join(', ')}] Å`:'Select a topic, then click an atom to inspect its coordinate record'}</div>
        <div className="bio-hub-cards absolute inset-x-3 bottom-3 z-20 grid grid-cols-5 gap-2">{filteredTopics.map(item=>{const data=topicData[item],Icon=data.icon;return <article key={item} className={`rounded border bg-[#071a29e8] p-2 backdrop-blur ${topic===item?'border-cyan-300':'border-white/15'}`}><button onClick={()=>setTopic(item)} className="flex w-full items-center gap-2 text-left"><Icon size={17} className="text-cyan-300"/><span><b className="block text-[11px]">{item}</b><small className="block text-[9px] text-slate-400">{data.id?`PDB ${data.id}`:`CID ${CARBOHYDRATE_CID}`}</small></span></button><button onClick={()=>onNavigate?.(data.route)} className="mt-2 w-full rounded border border-white/10 px-2 py-1 text-[9px] text-cyan-200">Open studio</button></article>})}</div>
      </main>
      <aside className="row-span-2 overflow-y-auto rounded-lg border border-white/10 bg-[#0a1e31] p-4"><h2 className="font-bold text-cyan-200">Learning route</h2>{topics.map((item,index)=><button key={item} onClick={()=>{setRoute(index+1);setTopic(item);}} className={`flex w-full items-center gap-3 border-b border-white/10 py-3 text-left text-xs ${route===index+1?'text-cyan-200':'text-slate-300'}`}><span className={`grid h-7 w-7 place-items-center rounded-full ${route===index+1?'bg-cyan-300 text-slate-900':'border border-white/20'}`}>{index+1}</span>{item}</button>)}<h2 className="mt-5 font-bold">Current structure</h2><div className="mt-2 rounded border border-cyan-300/20 bg-cyan-300/5 p-3 text-xs"><Database size={18} className="mb-2 text-cyan-300"/><b>{active.entity}</b><p className="mt-2 leading-5 text-slate-400">{active.subtitle}. This preview is loaded from a local coordinate file and rendered by Mol*.</p><p className="mt-2 text-cyan-200">{active.id?`PDB ${active.id}`:'PubChem CID 5793'}</p></div><button onClick={()=>onNavigate?.(active.route)} className="mt-4 w-full rounded bg-cyan-400/15 px-4 py-3 text-xs font-bold text-cyan-200">Open {topic} studio</button></aside>
      <section className="col-span-2 rounded-lg border border-white/10 bg-[#0a1e31] p-3"><div className="flex border-b border-white/10">{['Structure','Function','Dynamics','Sequence','Related'].map(item=><button key={item} onClick={()=>setTab(item)} className={`px-5 py-2 text-xs ${tab===item?'border-b-2 border-cyan-300 text-cyan-200':'text-slate-400'}`}>{item}</button>)}</div><div className="mt-3 flex items-center justify-between gap-4 text-xs"><div><b>{active.entity}</b><br/><span className="text-slate-400">{tab} · {active.metadata}</span></div><div className="rounded border border-white/10 px-4 py-2"><span className={ready?'text-emerald-300':'text-amber-200'}>{active.metric}: {ready?'Ready':'Loading'}</span></div><button onClick={()=>{if(active.ligand)viewerRef.current?.focusLigandId(active.ligand,'A');announce(`Inspecting ${active.action}`);}} className="rounded bg-blue-500 px-4 py-2 font-bold"><Play size={14} className="mr-2 inline"/>Inspect {active.action}</button></div></section>
    </div>{notice&&<div role="status" className="fixed bottom-4 right-5 z-50 rounded-full border border-cyan-300/40 bg-slate-950 px-4 py-2 text-xs">{notice}</div>}
  </div>;
}

const CARBOHYDRATE_CID = 5793;
