import { ArrowUpRight, Search, X, ChevronRight, Clock3, Signal, Rocket } from 'lucide-react';
import ConceptIcon from '../components/ConceptIcon.jsx';
import { categoryPng, subgroupPng, conceptPng } from '../data/homeIconManifest.js';
import { chemistryCategories, libraryEntries } from '../data/homeLibrary.js';
import { virtualLabCoverage, virtualLabExperimentCount, virtualLabStatusCounts } from '../data/virtualLabCoverage.js';
export default function HomeLibrary({query,setQuery,category,setCategory,subgroup,setSubgroup,onNavigate}) {
 const selected=chemistryCategories.find(c=>c.id===category);
 const words=query.trim().toLowerCase().split(/\s+/).filter(Boolean);
 const matches=e=>words.every(w=>`${e.title} ${e.description} ${e.subgroup} ${e.categoryTitle}`.toLowerCase().includes(w));
 const results=libraryEntries.filter(e=>(category==='all'||e.category===category)&&(subgroup==='all'||e.subgroup===subgroup)&&matches(e));
 const categoryHome={simulators:'virtual-labs',organic:'organic-chemistry',inorganic:'inorganic-chemistry',analytical:'analytical-chemistry'};
 const choose=id=>{if(categoryHome[id]){onNavigate(categoryHome[id]);return;}setCategory(id);setSubgroup('all')};
 const highlight=(text)=>{if(!words.length)return text;const pattern=new RegExp(`(${words.map(w=>w.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')).join('|')})`,'ig');return String(text).split(pattern).map((part,i)=>words.some(w=>part.toLowerCase()===w.toLowerCase())?<mark key={i}>{part}</mark>:part)};
 return <section className="home-library" id="home-library" aria-labelledby="library-title">
  <div className="library-heading"><div><span className="hub-eyebrow">YOUR CHEMISTRY WORKSPACE</span><h2 id="library-title">Explore the chemistry library<span>{libraryEntries.length} tools & experiences</span></h2><p>From your first atom to your next discovery. Choose a subject and dive in.</p></div><button className="library-reset" onClick={()=>{choose('all');setQuery('')}}>View all <ArrowUpRight size={16}/></button></div>
  <div className="library-categories" aria-label="Chemistry categories">{chemistryCategories.map(c=><button key={c.id} style={{'--category-color':c.color}} className={`library-category ${category===c.id?'selected':''}`} aria-pressed={category===c.id} onClick={()=>choose(c.id)}><ConceptIcon icon={categoryPng[c.id]}/><b>{c.title}</b><span>{c.groups.reduce((n,g)=>n+g.entries.length,0)} experiences <ChevronRight size={13}/></span><i className="library-category-glow" /></button>)}</div>
  <div className="library-browser"><div className="library-toolbar"><div className="library-breadcrumb"><button onClick={()=>choose('all')} aria-pressed={category==='all'}>All categories</button>{selected&&<><ChevronRight size={14}/><strong>{selected.title}</strong></>}</div><label className="library-search"><Search size={16}/><input aria-label="Search chemistry library" placeholder="Find a simulator, topic or tool…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear library search" onClick={()=>setQuery('')}><X size={14}/></button>}</label></div>
  {selected&&<div className="library-subcategories" aria-label="Subcategories"><button aria-pressed={subgroup==='all'} onClick={()=>setSubgroup('all')}>All {selected.title.toLowerCase()}</button>{selected.groups.map(g=><button key={g.name} aria-pressed={subgroup===g.name} onClick={()=>setSubgroup(g.name)}><ConceptIcon icon={subgroupPng[g.name]}/>{g.name}</button>)}</div>}
  <div className="library-result-count" role="status">{results.length} {results.length===1?'experience':'experiences'}{query&&<> matching “{query}”</>}{selected&&<span>{selected.description}</span>}</div>
  {results.length===0?<div className="library-empty"><Search size={30}/><h3>No matching experiences</h3><p>Try a topic such as gas, proteins, symmetry or reactions.</p><button onClick={()=>{choose('all');setQuery('')}}>Clear filters & browse all</button></div>:<div className="library-groups">{chemistryCategories.filter(c=>category==='all'||c.id===category).flatMap(c=>c.groups.map(g=>{const entries=results.filter(e=>e.category===c.id&&e.subgroup===g.name);return entries.length>0&&<section className="library-group" key={`${c.id}-${g.name}`} style={{'--category-color':c.color}}><header><ConceptIcon icon={subgroupPng[g.name]}/><div><span>{c.title}</span><h3>{g.name}</h3></div><small>{entries.length}</small></header><div>{entries.map((e,index)=><a href={e.upcoming ? undefined : `#/${e.path}`} aria-disabled={e.upcoming||undefined} className={e.upcoming ? 'library-entry-upcoming' : undefined} key={e.id} onClick={event=>{if(e.upcoming){event.preventDefault();return;}if(!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!event.altKey&&event.button===0){event.preventDefault();onNavigate(e.id)}}}><ConceptIcon icon={conceptPng[e.id]}/><div><b>{highlight(e.title)} {e.upcoming&&<em className="ml-2 rounded-full border border-amber-300/30 px-1.5 py-0.5 text-[9px] font-bold uppercase text-amber-200">Upcoming</em>}</b><p>{highlight(e.description)}</p><span className="library-entry-meta"><span><Clock3 size={11}/> {e.upcoming ? 'Planned' : index % 2 ? '12 min' : '8 min'}</span><span><Signal size={11}/> {e.kind || (index % 3 ? 'Interactive' : 'Guided')}</span></span></div>{e.upcoming ? <Rocket size={16}/> : <ArrowUpRight size={16}/>}</a>)}</div></section>}))}</div>}
 </div>
 <section className="mt-5 rounded-2xl border border-cyan-300/15 bg-cyan-950/20 p-4" aria-labelledby="vl-coverage-title">
  <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
   <div><span className="hub-eyebrow">REFERENCE COVERAGE CHECK</span><h2 id="vl-coverage-title" className="mt-1 text-lg font-black text-white">Chemical Sciences Virtual Labs</h2><p className="mt-1 text-xs text-gray-400">{virtualLabCoverage.length} virtual laboratories · {virtualLabExperimentCount} benchmark experiments</p></div>
   <div className="flex flex-wrap gap-2 text-[10px] font-bold"><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-emerald-200">Covered {virtualLabStatusCounts.covered}</span><span className="rounded-full bg-amber-400/10 px-2 py-1 text-amber-200">Partial {virtualLabStatusCounts.partial}</span><span className="rounded-full bg-rose-400/10 px-2 py-1 text-rose-200">Gap {virtualLabStatusCounts.gap}</span></div>
  </div>
  <div className="mt-3 grid gap-2 md:grid-cols-2">
   {virtualLabCoverage.map(lab=><details key={lab.id} className="rounded-xl border border-white/10 bg-black/15 p-3"><summary className="cursor-pointer list-none text-sm font-bold text-cyan-100">{lab.title}<span className="ml-2 text-[10px] font-normal text-gray-500">{lab.experiments.length} experiments</span></summary><div className="mt-3 space-y-1.5">{lab.experiments.map(([name,status])=><div key={name} className="flex items-start justify-between gap-3 text-xs"><span className="text-gray-300">{name}</span><span className={status==='covered'?'text-emerald-300':status==='partial'?'text-amber-300':'text-rose-300'}>{status}</span></div>)}<a className="mt-2 inline-block text-[11px] text-cyan-300 underline" href={lab.sourceUrl} target="_blank" rel="noreferrer">Open source lab ↗</a></div></details>)}
  </div>
 </section>
 <div className="library-bottom"><span><span className="library-dot"/> A whole world of chemistry. One place to explore.</span><a href="#/modules" onClick={e=>{e.preventDefault();onNavigate('subject-modules')}}>Explore subject modules <ArrowUpRight size={15}/></a></div>
 </section>
}

