import {useEffect,useRef,useState} from 'react';
import {FlaskConical,Home,Network,Boxes,BookOpen,NotebookPen,Settings,Play,Pause,RotateCcw,Menu,X,Calculator} from 'lucide-react';
import CobaltLabScene from '../components/inorganic/CobaltLabScene.jsx';
import {CrystalField,CobaltSpectrum} from '../components/inorganic/CobaltSciencePanels.jsx';
import {equilibrium} from '../components/inorganic/cobaltModel.js';
import './inorganicCobaltLab.css';

const presetStates=[{name:'Pink',chloride:.05,temp:25},{name:'Violet',chloride:1.136,temp:25},{name:'Blue',chloride:2,temp:60}];
const stamp=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
export default function InorganicDeepTargetPage({onNavigate}){
 const [chloride,setChloride]=useState(.5),[temp,setTemp]=useState(25),[tab,setTab]=useState('Investigation'),[noteTab,setNoteTab]=useState('Observations');
 const [motion,setMotion]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0);
 const [navOpen,setNavOpen]=useState(false),[notebookOpen,setNotebookOpen]=useState(false),[editor,setEditor]=useState(false),[draft,setDraft]=useState(''),[dialog,setDialog]=useState('');
 const [notes,setNotes]=useState(()=>{try{return JSON.parse(localStorage.getItem('cobalt-notebook-v1'))||[];}catch{return [];}});
 const [shown,setShown]=useState(equilibrium(.5,25).blue);
 const target=equilibrium(chloride,temp),first=useRef(true),dialogRef=useRef(null),notesRef=useRef(null);
 const record=(text,type='Observations')=>setNotes(v=>[{id:Date.now()+Math.random(),time:stamp(),text,type,chloride,temp},...v].slice(0,100));
 useEffect(()=>{try{localStorage.setItem('cobalt-notebook-v1',JSON.stringify(notes));}catch{}},[notes]);
 useEffect(()=>{if(first.current){first.current=false;return;}const timer=setTimeout(()=>record(`[Cl⁻] ${chloride.toFixed(3)} M · ${temp} °C. Model blue fraction ${(target.blue*100).toFixed(1)}%.`),650);return()=>clearTimeout(timer);},[chloride,temp]);
 useEffect(()=>{let id,last=performance.now();const animate=now=>{const dt=Math.min(.06,(now-last)/1000);last=now;if(!document.hidden){setShown(v=>Math.abs(v-target.blue)<.0001?target.blue:v+(target.blue-v)*(1-Math.exp(-dt*4)));if(playing&&motion)setProgress(v=>Math.min(1,v+dt/8));}id=requestAnimationFrame(animate);};id=requestAnimationFrame(animate);return()=>cancelAnimationFrame(id);},[target.blue,playing,motion]);
 useEffect(()=>{if(progress>=1)setPlaying(false);},[progress]);
 useEffect(()=>{setPlaying(false);setProgress(equilibrium(chloride,temp).blue);},[chloride,temp]);
 useEffect(()=>{if(dialog)dialogRef.current?.showModal();else dialogRef.current?.close();},[dialog]);
 const reset=()=>{setChloride(.5);setTemp(25);setProgress(0);setPlaying(false);};
 const restore=p=>{setChloride(p.chloride);setTemp(p.temp);setProgress(equilibrium(p.chloride,p.temp).blue);};
 const notebook=()=>{setNotebookOpen(true);setTimeout(()=>notesRef.current?.scrollIntoView({block:'nearest',behavior:'smooth'}),0);};
 const nav=[['Home',Home,'dashboard'],['Coordination Chemistry',Network,null],['Solid State Chemistry',Boxes,'inorganic-crystals'],['p-Block Chemistry',Boxes,'inorganic-pblock'],['Transition Metals',Network,'theory'],['Qualitative Analysis',FlaskConical,'inorganic-salt-analysis'],['Resources',BookOpen,'resources'],['Simulations',FlaskConical,'physical-simulators'],['Literature',BookOpen,'resources'],['Settings',Settings,'settings']];
 return <div className="cobalt-lab">
  <header className="cobalt-header"><button className="cobalt-mobile-menu" aria-label="Toggle navigation" onClick={()=>setNavOpen(v=>!v)}><Menu/></button><FlaskConical className="cobalt-logo"/><div><h1>Inorganic Chemistry Deep Lab</h1><p>Explore structure. Understand reactivity. See the invisible.</p></div><nav><span className="cobalt-lab-mode">● Lab Mode</span><button onClick={()=>{setNoteTab('Calculations');notebook();}}><Calculator size={15}/> Calculators</button><button onClick={()=>onNavigate?.('table')}>Periodic Table</button><button onClick={notebook}><NotebookPen size={15}/> Notes</button></nav><button className="cobalt-avatar" aria-label="About this lab" onClick={()=>setDialog('About this lab')}>JS</button></header>
  <div className="cobalt-layout">
   <aside className={'cobalt-nav '+(navOpen?'is-open':'')} aria-label="Inorganic navigation">{nav.map(([name,Icon,route])=><button key={name} className={name==='Coordination Chemistry'?'active':''} onClick={()=>{setNavOpen(false);if(route==='theory')setTab('Theory');else if(route==='resources'||route==='settings')setDialog(route==='settings'?'Settings':'Resources');else if(route)onNavigate?.(route);else setTab('Investigation');}}><Icon size={22}/><span>{name}</span></button>)}<p className="cobalt-nav-caption">Explore the geometry.<br/>Follow the evidence.<br/>Explain the colour.</p></aside>
   <main className="cobalt-main">
    <div className="cobalt-intro"><div><h2>Cobalt equilibrium</h2><p className="cobalt-equation">[Co(H₂O)₆]²⁺ ⇌ [CoCl₄]²⁻</p><p>Ligand substitution, colour change and Le Châtelier’s principle in action.</p></div><div className="cobalt-tabs" role="tablist" aria-label="Experiment sections">{['Investigation','Theory','Data','Playground'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div></div>
    {tab!=='Investigation'&&<section className="cobalt-context" role="tabpanel">{tab==='Theory'?<><strong>Ligand exchange changes geometry and colour.</strong> [Co(H₂O)₆]²⁺ + 4Cl⁻ ⇌ [CoCl₄]²⁻ + 6H₂O. Both complexes are high-spin d⁷ with three unpaired electrons. Heating favours the blue side. This is a simplified two-species teaching model.</>:tab==='Data'?<>Conditional K(T) = {target.k.toFixed(3)} · chloride activity approximated by [Cl⁻]/1 M · blue/pink = K(T)[Cl⁻]⁴ = {(target.k*chloride**4).toFixed(3)}. Model fractions are illustrative, not calibrated laboratory measurements.</>:<><strong>Try a condition:</strong>{presetStates.map(p=><button key={p.name} onClick={()=>restore(p)}>{p.name} state</button>)}</>}</section>}
    <section className="cobalt-hero">
     <div className="cobalt-vessel"><CobaltLabScene fraction={shown} motion={motion}/><div className="cobalt-geometry">Octahedral<br/><span>Co(II) · 6 × H₂O<br/>d⁷ (high spin)</span></div><div className="cobalt-vessel-label"><strong>[Co(H₂O)₆]²⁺ ⇌ [CoCl₄]²⁻</strong><span>Experimental sample · {(100-shown*100).toFixed(1)}% aqua / {(shown*100).toFixed(1)}% chloride</span></div></div>
     <div className="cobalt-control-wrap"><p className="cobalt-center-equation">[Co(H₂O)₆]²⁺ ⇌ [CoCl₄]²⁻</p><div className="cobalt-controls"><h3>Shift equilibrium</h3><label htmlFor="cobalt-chloride">[Cl⁻] concentration (M)<output>{chloride.toFixed(3)}</output></label><input id="cobalt-chloride" type="range" min=".001" max="2" step=".001" value={chloride} onChange={e=>setChloride(+e.target.value)}/><div className="cobalt-scale"><span>0.001</span><span>0.5</span><span>1</span><span>1.5</span><span>2 M</span></div><label htmlFor="cobalt-temperature">Temperature (°C)<output>{temp}</output></label><input id="cobalt-temperature" type="range" min="0" max="100" value={temp} onChange={e=>setTemp(+e.target.value)}/><div className="cobalt-scale"><span>0</span><span>25</span><span>50</span><span>75</span><span>100 °C</span></div><div className="cobalt-actions"><button aria-label="Add HCl (Cl⁻)" onClick={()=>setChloride(v=>Math.min(2,v+.25))} disabled={chloride>=2}><span>＋</span>Add HCl (Cl⁻)</button><button aria-label="Add H₂O (dilute)" onClick={()=>setChloride(v=>Math.max(.001,v/2))} disabled={chloride<=.001}><span>＋</span>Add H₂O (dilute)</button><button aria-label="Heat solution" onClick={()=>setTemp(v=>Math.min(100,v+10))} disabled={temp>=100}><span>↑</span>Heat solution</button></div><div className="cobalt-control-footer"><button onClick={()=>{setMotion(v=>!v);if(motion)setPlaying(false);}} aria-pressed={!motion}>{motion?<Pause size={13}/>:<Play size={13}/>} {motion?'Pause motion':'Resume motion'}</button><button onClick={reset}><RotateCcw size={13}/> Reset</button></div></div></div>
     <div className="cobalt-vessel"><CobaltLabScene kind="blue" fraction={1} motion={motion}/><div className="cobalt-geometry">Tetrahedral<br/><span>Co(II) · 4 × Cl⁻<br/>d⁷ (high spin)</span></div><div className="cobalt-vessel-label"><strong>[CoCl₄]²⁻</strong><span>(aq, blue) · chloride-rich reference</span></div></div>
    </section>
    <section className="cobalt-lower"><CrystalField/><CobaltSpectrum fraction={shown}/><section className="cobalt-panel cobalt-live"><h3>Live molecular view</h3><p>Ligand substitution · schematic pathway</p><CobaltLabScene kind="live" progress={progress} motion={motion}/><small>{progress<.3?'Chloride approaches the aqua complex':progress<.6?'Co–O coordination weakens; water leaves':progress<.95?'Chloride coordinates; tetrahedral geometry forms':'Tetrahedral chloride complex · water released'}</small><div className="cobalt-live-controls"><button aria-label={playing?'Pause substitution':'Play substitution'} onClick={()=>{if(progress>=1)setProgress(0);setMotion(true);setPlaying(v=>!v);}}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><input aria-label="Substitution progress" type="range" min="0" max="1" step=".01" value={progress} onChange={e=>{setPlaying(false);setProgress(+e.target.value);}}/><span>{(progress*8).toFixed(1)} / 8 s</span><button aria-label="Reset substitution" onClick={()=>{setPlaying(false);setProgress(0);}}><RotateCcw size={14}/></button></div><small>Illustrative animation time, not a measured reaction rate.</small></section></section>
   </main>
   <aside ref={notesRef} className={'cobalt-notebook '+(notebookOpen?'is-open':'')}><h2><NotebookPen size={21}/> Evidence Notebook <button onClick={()=>{setEditor(v=>!v);setNotebookOpen(true);}}>＋ New</button><button className="cobalt-notebook-close" aria-label="Close notebook" onClick={()=>setNotebookOpen(false)}><X size={17}/></button></h2><div className="cobalt-tabs" role="tablist" aria-label="Notebook sections">{['Observations','Calculations','Conclusions'].map(t=><button role="tab" aria-selected={noteTab===t} key={t} onClick={()=>setNoteTab(t)}>{t}</button>)}</div>
   {editor&&<form className="cobalt-note-editor" onSubmit={e=>{e.preventDefault();if(draft.trim()){record(draft.trim(),noteTab==='Conclusions'?'Conclusions':'Observations');setDraft('');setEditor(false);}}}><textarea aria-label="Notebook note" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Record your observation or conclusion…" required/><button type="submit">Save note</button></form>}
   <div className="cobalt-notebook-body">{noteTab==='Calculations'?<div className="cobalt-calculations"><h3>Conditional equilibrium model</h3><p>r = K(T) × ([Cl⁻] / 1 M)⁴</p><p>Blue fraction = r / (1 + r)</p><dl><dt>Temperature</dt><dd>{temp} °C</dd><dt>Chloride</dt><dd>{chloride.toFixed(3)} M</dd><dt>Model K(T)</dt><dd>{target.k.toFixed(3)}</dd><dt>Blue complex</dt><dd>{(shown*100).toFixed(1)}%</dd><dt>Aqua complex</dt><dd>{(100-shown*100).toFixed(1)}%</dd></dl><small>Illustrative K₂₉₈ = 0.6 and ΔH = +32 kJ/mol. Ignores intermediate complexes and nonideal activities. Do not use these fractions as quantitative experimental predictions.</small></div>:<div className="cobalt-observations">{notes.filter(n=>n.type===noteTab).slice(0,5).map(n=><article key={n.id}><time>{n.time}</time><p>{n.text}</p><button aria-label="Restore observation conditions" title="Restore conditions" onClick={()=>restore(n)}>↶</button></article>)}{!notes.some(n=>n.type===noteTab)&&<article><time>{stamp()}</time><p>{noteTab==='Conclusions'?'Add your conclusion using + New. Compare how heating and dilution affect the sample.':'Initial sample in water. Move a control to record a timestamped observation automatically.'}</p></article>}</div>}
   <div className="cobalt-evidence">{presetStates.map(p=><button aria-label={p.name} key={p.name} onClick={()=>restore(p)}><img src={'/assets/inorganic/cobalt-'+p.name.toLowerCase()+'.png'} alt={p.name+' solution — rendered reference'}/><span>{p.name}</span></button>)}<p>Rendered experiment references · click to restore conditions</p></div>
   <section className="cobalt-explanation"><h3>⚖ Le Châtelier’s explanation</h3><p>Increasing [Cl⁻] or temperature favours blue [CoCl₄]²⁻. Dilution or cooling favours pink [Co(H₂O)₆]²⁺. The system shifts to oppose the change.</p><p className="cobalt-live-result">Now: {(shown*100).toFixed(1)}% blue · {shown>.5?'chloride complex favoured':'aqua complex favoured'}</p></section><div className="cobalt-safety"><strong>Virtual experiment only</strong><p>Cobalt salts are toxic and concentrated HCl is corrosive. This simulation is not a home experiment guide.</p><button onClick={()=>setDialog('Resources')}>Sources & model limitations ↗</button></div></div></aside>
  </div>
  <dialog ref={dialogRef} className="cobalt-dialog" onCancel={()=>setDialog('')} onClose={()=>setDialog('')}><h2>{dialog}<button aria-label="Close dialog" onClick={()=>setDialog('')}><X/></button></h2>{dialog==='Settings'?<><p>Motion is {motion?'enabled':'paused'}. Reduced-motion preference is respected on startup.</p><button onClick={()=>setMotion(v=>!v)}>Toggle animation</button></>:<><p>A Three.js teaching laboratory with idealized octahedral and tetrahedral cobalt geometry. The right beaker is a fixed blue reference; the left sample responds to your controls.</p><p>The reference image's absorption-band ordering has been corrected: the pink aqua complex absorbs near 510 nm, while the blue chloride complex absorbs in the red region near 685 nm. Curves and equilibrium constants here are illustrative.</p><a target="_blank" rel="noreferrer" href="https://www.chem.indiana.edu/faculty-research/faculty-resources/chemistry-demos/demo/le-chateliers-principle-using-a-cobalt-complex/">Indiana University: cobalt equilibrium</a><a target="_blank" rel="noreferrer" href="https://paperspast.natlib.govt.nz/periodicals/TPRSNZ1948-77.2.6.1">Measured cobalt chloride absorption bands</a><a target="_blank" rel="noreferrer" href="https://chem.washington.edu/lecture-demos/cobalt-equilibrium">University of Washington: cobalt equilibrium and safety</a></>}</dialog>
 </div>;
}
