import { useMemo, useRef, useState } from "react";
import { Atom, BookOpen, Calculator, Download, FlaskConical, Home, Maximize2, PenTool, RotateCcw, Search, Sigma, Table2, Upload } from "lucide-react";
import MolstarViewer from "../components/molecular-viewer/MolstarViewer.jsx";
import ViewerErrorBoundary from "../components/molecular-viewer/ViewerErrorBoundary.jsx";

const nav = [[Home, "Home"], [Search, "Structure Search"], [FlaskConical, "Reactions"], [Table2, "Spectra"], [Calculator, "Property Calculator"], [Sigma, "Stoichiometry"], [PenTool, "Unit Converter"], [PenTool, "Drawing Canvas"], [BookOpen, "My Notebook"], [BookOpen, "Citations"]];
const properties = [["Molar mass", "194.19 g/mol"], ["Exact mass", "194.0804 Da"], ["LogP (XlogP3)", "−0.07"], ["Topological PSA", "58.44 Å²"], ["H-bond donors", "0"], ["H-bond acceptors", "3"], ["Rotatable bonds", "0"]];
const related = [["Theobromine", "C₇H₈N₄O₂", "CID 5428"], ["Theophylline", "C₇H₈N₄O₂", "CID 5429"], ["Paraxanthine", "C₇H₈N₄O₂", "CID 17754"]];
const samples = [
  { id: "2519", name: "Caffeine", detail: "PubChem 3D conformer", source: { url: "/assets/research-toolkit/caffeine-2519.sdf", label: "PubChem CID 2519 local cache" }, type: "sdf", representation: "BallAndStick" },
  { id: "1MBN", name: "Myoglobin", detail: "PDB coordinate sample", source: { url: "/assets/proteins/1MBN.pdb", label: "PDB 1MBN local cache" }, type: "pdb", representation: "Cartoon" },
  { id: "1BNA", name: "B-DNA dodecamer", detail: "mmCIF coordinate sample", source: { url: "/assets/nucleic-acid/structures/1BNA.cif", label: "PDB 1BNA local cache" }, type: "mmcif", representation: "BallAndStick" },
  { id: "5IKR", name: "COX-2 complex", detail: "Experimental ligand complex", source: { url: "/assets/drug-discovery/structures/5IKR.cif", label: "PDB 5IKR local cache" }, type: "mmcif", representation: "Cartoon" },
];
const smiles = "CN1C=NC2=C1C(=O)N(C(=O)N2C)C";
const inchi = "InChI=1S/C8H10N4O2/c1-10-4-9-6-5(10)7(13)12(3)8(14)11(6)2/h4H,1-3H3";

export const ResearchToolkitDashboardPage = () => {
  const viewerRef = useRef(null), uploadRef = useRef(null);
  const [tab, setTab] = useState("IR"), [notes, setNotes] = useState(""), [notice, setNotice] = useState("");
  const [mass, setMass] = useState("1.00"), [activeNav, setActiveNav] = useState("Home"), [query, setQuery] = useState("");
  const [sample, setSample] = useState(samples[0]), [representation, setRepresentation] = useState("BallAndStick");
  const [source, setSource] = useState(samples[0].source), [sourceType, setSourceType] = useState(samples[0].type), [label, setLabel] = useState("Caffeine · CID 2519");
  const [selectedAtom, setSelectedAtom] = useState(null), [measureMode, setMeasureMode] = useState(false), [measurementAtoms, setMeasurementAtoms] = useState([]);
  const spectrum = useMemo(() => tab === "IR" ? "IR · transmittance" : `${tab} · teaching trace`, [tab]);
  const mmol = Number.isFinite(Number(mass)) ? (Number(mass) / 194.19 * 1000).toFixed(4) : "—";
  const distance = measurementAtoms.length === 2 ? Math.hypot(...measurementAtoms[0].coordinates.map((value, index) => value - measurementAtoms[1].coordinates[index])).toFixed(2) : null;
  const representationState = useMemo(() => ({ [representation]: true }), [representation]);
  const announce = (text) => setNotice(text);

  const chooseSample = (next) => {
    setSample(next); setSource(next.source); setSourceType(next.type); setLabel(`${next.name} · ${next.id}`); setRepresentation(next.representation); setSelectedAtom(null); setMeasurementAtoms([]); announce(`${next.name} coordinate sample loaded`);
  };
  const runSearch = () => {
    const value = query.trim();
    const found = samples.find((item) => item.id.toLowerCase() === value.toLowerCase() || item.name.toLowerCase() === value.toLowerCase());
    if (found) return chooseSample(found);
    if (/^[0-9][a-z0-9]{3}$/i.test(value)) {
      const id = value.toUpperCase(); setSample(null); setSource({ url: `https://files.rcsb.org/download/${id}.cif`, label: `RCSB PDB ${id}` }); setSourceType("mmcif"); setLabel(`PDB ${id} · remote coordinates`); setRepresentation("Cartoon"); announce(`Loading RCSB PDB ${id}; local samples remain available`); return;
    }
    announce("No coordinate match. Try Caffeine, 1MBN, 1BNA, 5IKR, or a four-character PDB ID.");
  };
  const onSelection = (selection) => {
    setSelectedAtom(selection);
    if (!measureMode || !selection.coordinates) return;
    setMeasurementAtoms((current) => [...current.filter((item) => `${item.chain}:${item.residue}:${item.atom}` !== `${selection.chain}:${selection.residue}:${selection.atom}`), selection].slice(-2));
  };
  const loadUpload = async (event) => {
    const file = event.target.files?.[0]; if (!file) return;
    const ext = file.name.split(".").pop()?.toLowerCase();
    const normalized = ext === "cif" || ext === "mmcif" ? "mmcif" : ext;
    if (!new Set(["pdb", "mmcif", "sdf", "mol"]).has(normalized)) { announce("Unsupported format. Use PDB, mmCIF/CIF, MOL, or SDF."); event.target.value = ""; return; }
    setSample(null); setSource({ data: await file.text(), label: file.name }); setSourceType(normalized); setLabel(file.name); setRepresentation(normalized === "pdb" || normalized === "mmcif" ? "Cartoon" : "BallAndStick"); setSelectedAtom(null); setMeasurementAtoms([]); announce(`Loaded ${file.name} from this device`); event.target.value = "";
  };
  const saveViewerImage = async () => {
    const uri = await viewerRef.current?.png(); if (!uri) return announce("Viewer image is not ready yet.");
    const anchor = document.createElement("a"); anchor.href = uri; anchor.download = `${label.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-molstar.png`; anchor.click(); announce("Mol* image exported");
  };
  const exportCoordinates = async () => {
    try {
      const data = typeof source === "object" && source.data ? source.data : await fetch(source.url).then((response) => { if (!response.ok) throw new Error("Coordinate export failed"); return response.text(); });
      const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(new Blob([data], { type: "text/plain" })); anchor.download = source.label || `structure.${sourceType}`; anchor.click(); setTimeout(() => URL.revokeObjectURL(anchor.href), 1000); announce("Coordinate file exported");
    } catch (error) { announce(error.message); }
  };
  const copy = async (value, name) => { await navigator.clipboard?.writeText(value); announce(`${name} copied`); };

  return <div className="min-h-[calc(100vh-70px)] overflow-hidden bg-[#061526] text-slate-100">
    <header className="flex h-[68px] items-center gap-6 border-b border-white/10 bg-[#071a2b] px-6"><div className="flex items-center gap-3 text-xl font-black"><Atom className="text-sky-400" />Chemistry Research Toolkit</div><label className="mx-auto flex w-[600px] items-center gap-2 rounded border border-white/15 bg-black/20 px-4 py-2 text-sm text-slate-400"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === "Enter" && runSearch()} placeholder="Search local samples or enter a PDB ID" className="w-full bg-transparent outline-none" /></label><button onClick={() => uploadRef.current?.click()} className="flex items-center gap-2 text-sm"><Upload size={16} />Load</button><button onClick={() => announce("Help: load coordinates, select atoms, measure, annotate, and export")}>? Help</button><button onClick={() => announce("Local research profile opened")} className="rounded-full bg-sky-300 px-3 py-2 text-slate-900">●</button><input ref={uploadRef} type="file" accept=".pdb,.cif,.mmcif,.mol,.sdf" onChange={loadUpload} hidden /></header>
    <div className="grid min-h-[calc(100vh-138px)] grid-cols-[178px_1fr]"><aside className="border-r border-white/10 bg-[#071b2e] p-3"><nav className="space-y-1">{nav.map(([Icon, text]) => <button key={text} onClick={() => { setActiveNav(text); announce(`${text} workspace selected`); }} className={`flex w-full items-center gap-3 rounded px-3 py-3 text-left text-sm ${activeNav === text ? "border-l-4 border-sky-400 bg-sky-500/25" : "text-slate-300 hover:bg-white/5"}`}><Icon size={17} />{text}</button>)}</nav><p className="mt-16 px-3 text-sm text-sky-200">Build<br />Explore<br />Understand<br />Chemistry</p></aside>
      <main className="min-w-0 overflow-auto p-3">
        <section className="grid gap-3 rounded border border-white/10 bg-[#0b2034] p-4 xl:grid-cols-[1.05fr_1.45fr_280px]">
          <div><div className="flex items-start justify-between gap-2"><div><h1 className="text-3xl font-black">{sample?.name || label}</h1><p className="text-xl text-slate-300">{sample?.id === "2519" ? "C₈H₁₀N₄O₂" : "Coordinate structure"}</p><p className="text-sm text-slate-400">{sample?.id === "2519" ? "Molar mass 194.19 g/mol" : `${sourceType.toUpperCase()} source`}</p></div><span className="rounded border border-emerald-500/40 bg-emerald-500/10 px-2 py-1 text-[10px] text-emerald-300">COORDINATE-BACKED</span></div>{sample?.id === "2519" && <><div className="mt-4 flex flex-wrap gap-2">{["Xanthine", "Stimulant", "Plant metabolite", "CNS active"].map((text) => <span key={text} className="rounded border border-sky-300/30 px-3 py-1 text-xs">{text}</span>)}</div><p className="mt-4 max-w-lg text-sm text-slate-300">Caffeine (1,3,7-trimethylxanthine) is a natural xanthine alkaloid found in coffee, tea, cacao and other plants.</p></>}<div className="mt-4 grid gap-2"><b className="text-xs uppercase tracking-wider text-slate-400">Recent local structures</b>{samples.map((item) => <button key={item.id} onClick={() => chooseSample(item)} className={`flex justify-between rounded border px-3 py-2 text-left text-xs ${sample?.id === item.id ? "border-sky-400 bg-sky-500/15" : "border-white/10"}`}><span>{item.name}<small className="block text-slate-400">{item.detail}</small></span><code>{item.id}</code></button>)}</div></div>
          <div className="min-h-[310px] overflow-hidden rounded border border-white/10 bg-[#050f18]"><div className="h-[265px]"><ViewerErrorBoundary><MolstarViewer ref={viewerRef} source={source} sourceType={sourceType} label={label} pdbId={sample && sample.type !== "sdf" && /^[0-9][A-Z0-9]{3}$/.test(sample.id) ? sample.id : undefined} representation={representationState} colorScheme="element" showLabels={false} onSelectionChange={onSelection} onLoadError={(error) => announce(error.message)} /></ViewerErrorBoundary></div><div className="flex flex-wrap items-center gap-1 border-t border-white/10 p-2">{["BallAndStick", "Licorice", "Spacefill", "Cartoon", "Surface"].map((style) => <button key={style} onClick={() => setRepresentation(style)} className={`rounded border px-2 py-1 text-[10px] ${representation === style ? "border-sky-400 bg-sky-500/25" : "border-white/10"}`}>{style === "BallAndStick" ? "Ball & stick" : style}</button>)}<button className={`rounded border px-2 py-1 text-[10px] ${measureMode ? "border-amber-400 bg-amber-500/20" : "border-white/10"}`} onClick={() => { setMeasureMode((value) => !value); setMeasurementAtoms([]); }}>Measure</button><button aria-label="Reset structure camera" onClick={() => viewerRef.current?.reset()} className="rounded border border-white/10 p-1"><RotateCcw size={13} /></button><button aria-label="Fullscreen structure viewer" onClick={() => viewerRef.current?.fullscreen()} className="rounded border border-white/10 p-1"><Maximize2 size={13} /></button><button aria-label="Export viewer image" onClick={saveViewerImage} className="rounded border border-white/10 p-1"><Download size={13} /></button></div><div className="border-t border-white/10 px-3 py-2 font-mono text-[10px] text-slate-400">{selectedAtom ? `${selectedAtom.residueName} ${selectedAtom.residue} · chain ${selectedAtom.chain || "—"} · ${selectedAtom.atom} (${selectedAtom.element})` : "Select an atom for coordinate details"}{measureMode && <span className="ml-3 text-amber-300">{distance ? `Calculated distance ${distance} Å` : `Select ${2 - measurementAtoms.length} atom(s)`}</span>}</div></div>
          <div className="rounded border border-white/10 bg-black/15 p-3"><b>Source &amp; Provenance</b>{[["PubChem", "CID 2519", sample?.id === "2519" ? "3D conformer" : "Caffeine reference"], ["Local cache", source.label || label, source.url?.startsWith("/") || source.data ? "Available offline" : "Remote source"], ["RCSB PDB", "Only for PDB samples", sample && sample.type !== "sdf" && /^[0-9][A-Z0-9]{3}$/.test(sample.id) ? sample.id : "Not applicable"]].map(([a, b, c]) => <div key={a} className="mt-3 flex justify-between gap-2 text-xs"><span>◉ {a}<small className="block break-all text-slate-400">{b}</small></span><span className="text-right text-emerald-300">{c}</span></div>)}<div className="mt-4 border-t border-white/10 pt-3"><b>Export</b><div className="mt-2 flex flex-wrap gap-2"><button onClick={exportCoordinates} className="rounded border border-white/15 px-2 py-1 text-xs">Coordinates</button><button onClick={() => copy(smiles, "SMILES")} className="rounded border border-white/15 px-2 py-1 text-xs">SMILES</button><button onClick={() => copy(inchi, "InChI")} className="rounded border border-white/15 px-2 py-1 text-xs">InChI</button></div></div></div>
        </section>

        <div className="mt-3 grid gap-3 xl:grid-cols-[230px_1.7fr_1fr_270px]">
          <section className="rounded border border-white/10 bg-[#0b2034] p-3"><h2 className="font-bold">Property Calculator</h2>{properties.map(([name, value]) => <div key={name} className="flex justify-between border-b border-white/10 py-2 text-xs"><span className="text-slate-400">{name}</span><b>{value}</b></div>)}<button onClick={() => announce("PubChem-computed properties reviewed")} className="mt-4 w-full rounded border border-white/15 px-3 py-2 text-xs">⊞ Calculate properties</button></section>
          <section className="rounded border border-white/10 bg-[#0b2034] p-3"><div className="flex items-center justify-between gap-2"><h2 className="font-bold">▥ Spectra Viewer</h2><div className="flex gap-1">{["IR", "¹H NMR", "¹³C NMR", "MS"].map((item) => <button key={item} onClick={() => { setTab(item); announce(`${item} spectrum selected`); }} className={`rounded border px-3 py-1 text-xs ${tab === item ? "border-blue-400 bg-blue-500" : "border-white/15"}`}>{item}</button>)}</div></div><p className="mt-2 text-right text-xs text-sky-300">{spectrum}</p><Spectrum /><div className="grid grid-cols-3 gap-2 text-xs text-slate-300"><span>1695 · C=O stretch</span><span>1620 · C=N stretch</span><span>1450 · CH₃ bend</span></div></section>
          <section className="space-y-3"><div className="rounded border border-white/10 bg-[#0b2034] p-3"><h2 className="font-bold">⌕ Reaction Search</h2><input className="mt-3 w-full rounded border border-white/15 bg-black/20 px-3 py-2 text-sm" defaultValue="Caffeine" /><button onClick={() => announce("Reaction search results updated") } className="mt-2 rounded bg-blue-500 px-3 py-2 text-xs">Search reactions</button><p className="mt-2 text-xs text-slate-400">Examples: oxidation, demethylation, synthesis</p></div><div className="rounded border border-white/10 bg-[#0b2034] p-3"><h2 className="font-bold">Stoichiometry Notebook</h2><p className="mt-3 text-sm">C₈H₁₀N₄O₂ + 2 O₂ → 8 CO₂ + 5 H₂O + 4 N₂</p><label className="mt-2 block text-xs">Mass of caffeine<input value={mass} onChange={(event) => setMass(event.target.value)} className="ml-3 w-24 rounded border border-white/15 bg-black/20 px-2 py-1" /> g</label><p className="mt-2 text-xs text-sky-300">Amount: {mmol} mmol</p><button onClick={() => announce(`Stoichiometry calculated for ${mass} g`)} className="mt-3 w-full rounded border border-white/15 py-2 text-xs">Calculate</button></div></section>
          <aside className="space-y-3"><div className="rounded border border-white/10 bg-[#0b2034] p-3"><h2 className="font-bold">↔ Unit Converter</h2><select className="mt-3 w-full rounded border border-white/15 bg-black/20 p-2 text-xs"><option>Mass → amount</option></select><p className="mt-3 text-xs">{mass || "0"} g = <b className="text-sky-300">{mmol} mmol</b></p><p className="mt-1 text-xs text-slate-400">Using 194.19 g/mol</p></div><div className="rounded border border-white/10 bg-[#0b2034] p-3"><h2 className="font-bold">✎ Drawing Canvas</h2><div className="mt-2 flex h-32 items-center justify-center rounded border border-white/10"><Caffeine2D /></div><button onClick={() => announce("2D drawing saved to the current session")} className="mt-2 rounded border border-white/15 px-3 py-1 text-xs">Save drawing</button></div><div className="rounded border border-white/10 bg-[#0b2034] p-3"><h2 className="font-bold">Related Compounds</h2>{related.map((item) => <button key={item[0]} onClick={() => announce(`${item[0]} selected; validated coordinates are not cached yet`)} className="mt-2 flex w-full items-center justify-between text-left text-xs"><span>◉ {item[0]}<small className="block text-slate-400">{item[1]}</small></span><span>{item[2]} ›</span></button>)}</div></aside>
        </div>
        <section className="mt-3 grid gap-3 xl:grid-cols-2"><div className="rounded border border-white/10 bg-[#0b2034] p-3"><h2 className="font-bold">Citation Notebook</h2><p className="mt-3 text-xs text-slate-400">PubChem. Caffeine (CID 2519). National Center for Biotechnology Information. Accessed 2026-09-09.</p><button onClick={() => { setNotes((value) => `${value}${value ? "\n" : ""}Citation: PubChem CID 2519, accessed 2026-09-09.`); announce("Citation added to notes"); }} className="mt-3 rounded border border-white/15 px-3 py-2 text-xs">Add to notebook</button></div><div className="rounded border border-white/10 bg-[#0b2034] p-3"><h2 className="font-bold">Research Notes</h2><textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Record provenance, observations, limitations, and next steps..." className="mt-3 h-24 w-full rounded border border-white/15 bg-black/20 p-2 text-sm" /></div></section>
      </main>
    </div>{notice && <div role="status" className="fixed bottom-4 right-5 z-50 flex items-center gap-3 rounded border border-sky-300/40 bg-[#0b223d] px-4 py-2 text-xs text-sky-100"><span>{notice}</span><button aria-label="Dismiss notice" onClick={() => setNotice("")}>×</button></div>}
  </div>;
};

function Caffeine2D() { return <svg viewBox="0 0 260 150" className="h-full w-full" aria-label="2D caffeine structure"><g fill="none" stroke="#cfe4f4" strokeWidth="2"><path d="M62 40l44-22 39 25-5 48-45 18-38-28zM145 43l37 18-3 42-39-12M72 48l30-16M65 75l28 22M151 50l25 13M172 92l-25-4M95 109l-7 30M140 91l9 39M106 18l-4-16M182 61l31-18" /></g><g fill="#60c7ff" fontFamily="IBM Plex Mono, monospace" fontSize="13"><text x="99" y="62">N</text><text x="132" y="49">N</text><text x="132" y="100">N</text><text x="173" y="87">N</text></g><g fill="#ff6570" fontFamily="IBM Plex Mono, monospace" fontSize="13"><text x="76" y="147">O</text><text x="144" y="145">O</text></g><g fill="#dbeafe" fontSize="11"><text x="82" y="12">CH₃</text><text x="211" y="44">CH₃</text></g></svg>; }
function Spectrum() { return <svg viewBox="0 0 650 220" className="h-52 w-full" aria-label="Interactive teaching spectrum"><path d="M45 20V180H630" fill="none" stroke="#8294b1" /><path d="M45 60H630M45 100H630M45 140H630M130 20V180M230 20V180M330 20V180M430 20V180M530 20V180" fill="none" stroke="#243c56" strokeDasharray="3 5" /><path d="M46 57 C120 45 145 48 165 80 S180 177 202 63 S240 53 262 70 S289 145 310 61 S340 52 365 105 S389 170 410 63 S438 43 450 72 S470 150 489 60 S514 52 540 93 S565 172 585 59 S607 52 630 70" fill="none" stroke="#26b7ff" strokeWidth="3" /><line x1="410" y1="20" x2="410" y2="180" stroke="#fbbf24" strokeDasharray="4 4" /><text x="422" y="45" fill="#fbbf24" fontSize="13">1695 cm⁻¹</text><text x="50" y="205" fill="#9eb0c9" fontSize="12">4000</text><text x="590" y="205" fill="#9eb0c9" fontSize="12">500</text></svg>; }
export default ResearchToolkitDashboardPage;
