import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Beaker, CheckCircle2, FlaskConical, Maximize2, Snowflake, Thermometer, Wind } from "lucide-react";
import PharmaLabShell from "./components/PharmaLabShell.jsx";
import UnitInput from "./components/UnitInput.jsx";
import ExperimentControls from "./components/ExperimentControls.jsx";
import SynthesisApparatus from "./components/SynthesisApparatus.jsx";
import { atomEconomy, calculateEquivalents, calculateLiquidMoles, calculateMoles, eFactor, findLimitingReagent, percentageYield, theoreticalYield } from "./calculations/scientificCalculations.js";
import { estimateParacetamolConversion, nextSynthesisStage, synthesisSteps as steps } from "./simulation/synthesisModel.js";
import "./pharmaLab.css";
import "./apiSynthesis.css";
import "./apiSynthesisTitle.css";

const sourceUrl="https://pubchem.ncbi.nlm.nih.gov/compound/Acetic-anhydride";
const savedSynthesis=()=>{try{return JSON.parse(localStorage.getItem("chemistry-universe:api-synthesis:v1"))||{}}catch{return{}}};

export default function ApiSynthesisPage(){
 const tick=useRef(null),apparatusPanel=useRef(null); const saved=useMemo(savedSynthesis,[]); const [query,setQuery]=useState(""); const [mass,setMass]=useState(saved.mass??5); const [volume,setVolume]=useState(saved.volume??5); const [temperature,setTemperature]=useState(saved.temperature??25); const [rpm,setRpm]=useState(saved.rpm??350); const [elapsed,setElapsed]=useState(saved.elapsed??0); const [stage,setStage]=useState(saved.stage??0); const [running,setRunning]=useState(false); const [started,setStarted]=useState((saved.elapsed??0)>0); const [speed,setSpeed]=useState(1); const [message,setMessage]=useState(saved.stage?"Restored the last locally saved experiment state.":"Verify glassware, cooling water and PPE before charging."); const [tlc,setTlc]=useState(saved.tlc??[]); const [sources,setSources]=useState(false); const [motion,setMotion]=useState(false); const [mode,setMode]=useState("guided");
 const calc=useMemo(()=>{try{const amine=calculateMoles({mass,molarMass:109.13});const anhydride=calculateLiquidMoles({volume,density:1.082,molarMass:102.09});const limiting=findLimitingReagent([{name:"p-aminophenol",moles:amine,coefficient:1},{name:"acetic anhydride",moles:anhydride,coefficient:1}]);const theo=theoreticalYield({limitingMoles:limiting.moles,productMolarMass:151.16});const conversion=estimateParacetamolConversion({elapsedMinutes:elapsed,temperatureCelsius:stage>=4?85:temperature});const recovered=stage>=7?theo.grams*conversion/100*.91:0;return{amine,anhydride,equiv:calculateEquivalents(anhydride,amine),limiting,theo,conversion,recovered,yield:recovered?percentageYield(recovered,theo.grams):0,atom:atomEconomy(151.16,109.13+102.09),ef:recovered?eFactor({inputMassGrams:mass+volume*1.082+20,isolatedProductGrams:recovered}):null}}catch(error){return{error:error.message,conversion:0}}},[mass,volume,elapsed,temperature,stage]);
 useEffect(()=>{clearInterval(tick.current);if(running)tick.current=setInterval(()=>setElapsed(v=>Math.min(60,v+.5*speed)),200);return()=>clearInterval(tick.current)},[running,speed]);
 useEffect(()=>{if(elapsed>=45&&running){setRunning(false);setMessage("Reaction hold complete. Take a TLC sample, then begin controlled cooling.")}},[elapsed,running]);
 useEffect(()=>localStorage.setItem("chemistry-universe:api-synthesis:v1",JSON.stringify({mass,volume,temperature,rpm,elapsed,stage,tlc})),[mass,volume,temperature,rpm,elapsed,stage,tlc]);
 const reset=()=>{setMass(5);setVolume(5);setTemperature(25);setRpm(350);setElapsed(0);setStage(0);setRunning(false);setStarted(false);setTlc([]);setMessage("Verify glassware, cooling water and PPE before charging.")};
 const advance=()=>{
  if(calc.error)return setMessage(calc.error);
  const transition=nextSynthesisStage({stage,equivalents:calc.equiv,rpm,conversion:calc.conversion}); if(transition.validation)return setMessage(transition.validation);
  const next=transition.stage;setStage(next);setRunning(false);setMessage(["Glassware verified. Weigh and charge p-aminophenol.","p-Aminophenol charged. Add acetic anhydride slowly below 40 °C.","Reagents charged. Start stirring and raise the mantle setpoint.","Maintain 80–90 °C and monitor conversion.","Cooling initiated. Transfer to an ice bath below 10 °C.","Crystals formed. Prepare the Büchner filtration train.","Vacuum filtration active. Wash the cake with cold water.","Dry the product to constant mass.","Synthesis and isolation complete."][next]);
  if(next===3)setTemperature(85); if(next===4)setTemperature(35); if(next===5)setTemperature(8);
 };
 const toggle=()=>{setStarted(true);if(stage!==3)return setMessage("Playback is available during Heat & react. Use Step to complete the current setup operation.");if(temperature<60||temperature>95)return setMessage("Set 60–95 °C before starting. The guided preset is 85 °C.");setRunning(v=>!v)};
 const sampleTlc=()=>{if(stage<3)return setMessage("TLC sampling is locked until the reaction has started.");setTlc(v=>[...v.slice(-3),{time:elapsed,conversion:calc.conversion}]);setMessage(`TLC sampled at ${elapsed.toFixed(1)} min. Educational spot intensity updated from the conversion model.`)};
 return <PharmaLabShell query={query} setQuery={setQuery} activeStage={2} onReset={reset} onSave={()=>setMessage("Experiment state saved locally.")} onSources={()=>setSources(true)} reducedMotion={motion} setReducedMotion={setMotion}>
  <main className="plab-synth">
   <header className="plab-page-title"><div><span className="plab-panel-kicker">STAGE 03 · API SYNTHESIS</span><h1>Paracetamol API Synthesis</h1><p>p-aminophenol + acetic anhydride → paracetamol + acetic acid</p></div><div className="plab-mode"><button className={mode==="guided"?"active":""} onClick={()=>setMode("guided")}>Guided</button><button className={mode==="free"?"active":""} onClick={()=>setMode("free")}>Free experiment</button></div></header>
   <div className="plab-synth-grid">
    <aside className="plab-reagents"><span className="plab-panel-kicker">STOICHIOMETRY</span><h2>Reagent charge</h2><UnitInput label="p-Aminophenol" help="PubChem CID 403 · MW 109.13" value={mass} onChange={setMass} unit="g" units={["g"]} min={0.1} max={25}/><UnitInput label="Acetic anhydride" help="PubChem CID 7918 · ρ 1.082 g/mL at 20 °C" value={volume} onChange={setVolume} unit="mL" units={["mL"]} min={0.1} max={30}/><div className="plab-equation"><b>1 : 1 acetylation</b><span>{calc.amine?.toFixed(4)} mol</span><span>{calc.anhydride?.toFixed(4)} mol</span></div><dl><div><dt>Anhydride equivalents</dt><dd>{calc.equiv?.toFixed(2)} eq</dd></div><div><dt>Limiting reagent</dt><dd>{calc.limiting?.name}</dd></div><div><dt>Theoretical yield</dt><dd>{calc.theo?.grams.toFixed(2)} g</dd></div></dl><div className="plab-safety-warning"><AlertTriangle/><span><b>Corrosive reagent</b><small>Add acetic anhydride slowly with cooling and ventilation. This is a teaching simulation; follow an approved SOP in a real lab.</small></span></div>
    <div className="plab-step-list">{steps.map((item,index)=><button key={item} className={index===stage?"active":index<stage?"done":""} onClick={()=>mode==="free"&&index<=stage+1&&setStage(index)}><span>{index<stage?"✓":index+1}</span>{item}</button>)}</div></aside>
    <section className="plab-apparatus" ref={apparatusPanel}><div className="plab-instrument-head"><span><FlaskConical/> Reaction & isolation train</span><span>{steps[stage]} <button title="Fullscreen apparatus" onClick={()=>apparatusPanel.current?.requestFullscreen?.()}><Maximize2/></button></span></div><SynthesisApparatus stage={stage} running={running} rpm={rpm} temperature={temperature} conversion={calc.conversion} reducedMotion={motion}/><div className="plab-live-strip"><span><Thermometer/> <b>{temperature} °C</b> probe</span><span><Wind/> <b>{rpm} rpm</b> stirrer</span><span><Beaker/> <b>{calc.conversion?.toFixed(1)}%</b> conversion</span><span><Snowflake/> <b>{stage===5?"ICE":"OFF"}</b> bath</span></div></section>
    <aside className="plab-process"><span className="plab-panel-kicker">LIVE PROCESS</span><h2>{steps[stage]}</h2><div className="plab-conversion-ring" style={{"--progress":`${calc.conversion*3.6}deg`}}><strong>{calc.conversion?.toFixed(0)}%</strong><small>conversion model</small></div><UnitInput label="Temperature" value={temperature} onChange={setTemperature} unit="°C" units={["°C"]} min={0} max={110}/><UnitInput label="Stirring" value={rpm} onChange={setRpm} unit="rpm" units={["rpm"]} min={0} max={900}/><UnitInput label="Reaction time" value={elapsed.toFixed(1)} onChange={setElapsed} unit="min" units={["min"]} min={0} max={60}/><ExperimentControls running={running} started={started} onToggle={toggle} onStep={advance} onReset={reset} speed={speed} onSpeedChange={setSpeed}/><button className="plab-tlc-button" onClick={sampleTlc}>Take TLC sample</button><div className="plab-validation" role="status"><CheckCircle2/><span><b>Guidance</b><small>{message}</small></span></div></aside>
   </div>
   <section className="plab-synth-results"><div className="plab-tlc"><span><span className="plab-panel-kicker">TLC MONITOR</span><h2>Reaction progress</h2></span><div className="plab-tlc-plate">{tlc.length?tlc.map((sample,index)=><i key={`${sample.time}-${index}`} style={{left:`${18+index*23}%`,bottom:`${18+sample.conversion*.55}%`,opacity:.35+sample.conversion/155}} title={`${sample.time.toFixed(1)} min · ${sample.conversion.toFixed(1)}%`}/>):<small>Take a sample during reaction</small>}</div></div>{[["Isolated mass",calc.recovered?`${calc.recovered.toFixed(2)} g`:"—"],["Percent yield",calc.yield?`${calc.yield.toFixed(1)}%`:"—"],["Mass balance",calc.recovered?`${Math.min(100,calc.yield+10).toFixed(1)}%`:"—"],["Atom economy",`${calc.atom?.toFixed(1)}%`],["E-factor",calc.ef?calc.ef.toFixed(2):"—"]].map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong><span>{a==="Atom economy"?"Calculated from balanced equation":"Representative educational result"}</span></article>)}</section>
  </main>{sources&&<div className="plab-drawer-backdrop" onClick={()=>setSources(false)}><aside className="plab-drawer" onClick={e=>e.stopPropagation()}><span className="plab-panel-kicker">PAGE 3 PROVENANCE</span><h2>Reaction data sources</h2><p>Molar masses and acetic anhydride density are traceable to PubChem. Kinetics, recovery, TLC intensity and process results are representative educational models.</p><a href="https://pubchem.ncbi.nlm.nih.gov/compound/4-Aminophenol" target="_blank" rel="noreferrer">4-Aminophenol · PubChem CID 403</a><a href={sourceUrl} target="_blank" rel="noreferrer">Acetic anhydride · PubChem CID 7918</a><a href="https://pubchem.ncbi.nlm.nih.gov/compound/Acetaminophen" target="_blank" rel="noreferrer">Acetaminophen · PubChem CID 1983</a><button className="plab-export" onClick={()=>setSources(false)}>Close source panel</button></aside></div>}
 </PharmaLabShell>
}
