import { useEffect, useRef, useState } from "react";
import { Activity, Atom, Pause, Play, RotateCcw, SkipForward } from "lucide-react";
import PharmaLabShell from "./components/PharmaLabShell.jsx";
import MolstarViewer from "../../components/molecular-viewer/MolstarViewer.jsx";
import ViewerErrorBoundary from "../../components/molecular-viewer/ViewerErrorBoundary.jsx";
import "./pharmaLab.css";
import "./medicinalChemistry.css";
import "./medicinalScience.css";

const analogs=[
  ["Atorvastatin","8.7 / 10",8.7,"Reference"],["Rosuvastatin","9.1 / 10",9.1,"Polar head"],["Simvastatin","7.5 / 10",7.5,"Lactone"],["Pravastatin","6.9 / 10",6.9,"Hydrophilic"]
];

export default function MedicinalChemistryPage(){
 const viewer=useRef(null); const timer=useRef(null); const [query,setQuery]=useState(""); const [running,setRunning]=useState(false); const [started,setStarted]=useState(false); const [step,setStep]=useState(0); const [speed,setSpeed]=useState(1); const [pose,setPose]=useState(0); const [style,setStyle]=useState("Surface"); const [motion,setMotion]=useState(false); const [sources,setSources]=useState(false);
 useEffect(()=>{clearInterval(timer.current);if(running)timer.current=setInterval(()=>setPose(v=>(v+1)%4),900/speed);return()=>clearInterval(timer.current)},[running,speed]);
 const advance=()=>{setStarted(true);setStep(v=>Math.min(4,v+1));setPose(v=>(v+1)%4);viewer.current?.rotate("y",14)};
 const reset=()=>{setRunning(false);setStarted(false);setStep(0);setPose(0);viewer.current?.reset()};
 return <PharmaLabShell query={query} setQuery={setQuery} activeStage={1} onReset={reset} onSave={()=>setSources(true)} onSources={()=>setSources(true)} reducedMotion={motion} setReducedMotion={setMotion}>
  <main className="plab-medchem">
   <header className="plab-page-title"><div><span className="plab-panel-kicker">STAGE 02 · LEAD OPTIMIZATION</span><h1>Medicinal Chemistry Studio</h1><p>Optimize atorvastatin inside its experimentally determined human target complex.</p></div><span className="plab-evidence">EXPERIMENTAL · PDB 1HWK · 2.22 Å</span></header>
   <div className="plab-med-grid">
    <aside className="plab-med-side"><span className="plab-panel-kicker">LEAD SERIES</span><h2>Atorvastatin</h2><p>HMG-CoA reductase inhibitor</p><div className="plab-line-structure">F–Ph<br/>╲　 pyrrole—CONHPh<br/>　╲━━(OH)━(OH)━CO₂H</div><dl><div><dt>Formula</dt><dd>C₃₃H₃₅FN₂O₅</dd></div><div><dt>MW</dt><dd>558.6 g/mol</dd></div><div><dt>XLogP3-AA</dt><dd>5.0</dd></div><div><dt>TPSA</dt><dd>112 Å²</dd></div><div><dt>HBD / HBA</dt><dd>4 / 6</dd></div><div><dt>Rotatable bonds</dt><dd>12</dd></div><div><dt>Lipinski / Veber</dt><dd>1 / 1 alert</dd></div></dl><div className="plab-objective"><b>Optimization objective</b><p>Retain the dihydroxy acid pharmacophore while balancing potency, exposure and selectivity.</p></div></aside>
    <section className="plab-pocket"><div className="plab-pocket-head"><span><Atom/> HMG-CoA reductase binding pocket</span><div>{["Surface","Cartoon","Atoms"].map(x=><button className={style===x?"active":""} onClick={()=>setStyle(x)} key={x}>{x}</button>)}</div></div><div className="plab-pocket-view"><ViewerErrorBoundary label="HMG-CoA reductase atorvastatin complex"><MolstarViewer ref={viewer} source={{url:"/assets/pharma/1HWK.pdb",format:"pdb"}} sourceType="pdb" label="Human HMG-CoA reductase · atorvastatin" pdbId="1HWK" focusLigandId="117" focusLigandChain="A" representation={{Surface:style==="Surface",Cartoon:style==="Cartoon",BallAndStick:style==="Atoms",Ligand:true,Ion:true}} colorScheme="chain" onReady={()=>viewer.current?.focusLigandId("117","A")}/></ViewerErrorBoundary><div className="plab-pocket-tag">Ligand 117 · chain A · residue 2</div></div><div className="plab-interactions"><span>Ser684 OG · 2.65 Å</span><span>Arg590 NE · 2.77 Å</span><span>Asp690 OD2 · 2.79 Å</span><span>Lys691 NZ · 2.84 Å</span><span>Val683 CG1 · 3.29 Å</span></div></section>
    <aside className="plab-docking"><span className="plab-panel-kicker">DOCKING & INTERACTIONS</span><h2>Pose {pose+1} of 4</h2><div className="plab-score"><strong>{(-9.4+pose*.18).toFixed(2)}</strong><small>kcal/mol · illustrative pose heuristic v1</small></div>{[["H-bonds",4-pose%2],["Hydrophobic contacts",7+pose],["Steric alerts",pose===3?1:0]].map(([a,b])=><div className="plab-metric" key={a}><span>{a}</span><b>{b}</b></div>)}<label>Search speed <input type="range" min=".5" max="2" step=".5" value={speed} onChange={e=>setSpeed(+e.target.value)}/>{speed}×</label><div className="plab-run-controls"><button onClick={()=>{setStarted(true);setRunning(!running)}}>{running?<Pause/>:<Play/>}{running?"Pause":started?"Resume":"Start"}</button><button onClick={advance}><SkipForward/>Step</button><button onClick={reset}><RotateCcw/>Reset</button></div><div className="plab-guidance"><b>Guided optimization · {step}/4</b><p>{["Inspect the reference complex.","Compare conserved polar contacts.","Evaluate lipophilic pocket occupancy.","Check developability trade-offs.","Lead review complete."][step]}</p></div></aside>
   </div>
   <section className="plab-sar"><div><span className="plab-panel-kicker">STRUCTURE–ACTIVITY RELATIONSHIP</span><h2>Statin analog comparison</h2><small>Representative educational indices</small></div><table><thead><tr><th>Analog</th><th>Potency index</th><th>Developability score</th><th>Design note</th></tr></thead><tbody>{analogs.filter(x=>x.join(" ").toLowerCase().includes(query.toLowerCase())).map(x=><tr key={x[0]}><td>{x[0]}</td><td>{x[1]}</td><td><span className="plab-bar"><i style={{width:`${x[2]*10}%`}}/></span>{x[2]}</td><td>{x[3]}</td></tr>)}</tbody></table><aside><Activity/><b>Decision</b><p>Advance atorvastatin as the reference lead. Explore polar analogs when exposure or transporter behavior becomes limiting.</p></aside></section>
  </main>{sources&&<div className="plab-drawer-backdrop" onClick={()=>setSources(false)}><aside className="plab-drawer" onClick={e=>e.stopPropagation()}><h2>Page 2 evidence</h2><p>Structure: RCSB PDB 1HWK, human HMG-CoA reductase–atorvastatin complex, X-ray diffraction, 2.22 Å. Contact distances are calculated directly from local chain-A coordinates with a 4.5 Å cutoff. Pose and SAR scores are representative educational heuristics, not experimental measurements.</p><a href="https://www.rcsb.org/structure/1HWK" target="_blank" rel="noreferrer">RCSB PDB 1HWK</a><a href="https://pubchem.ncbi.nlm.nih.gov/compound/60823" target="_blank" rel="noreferrer">PubChem CID 60823 descriptors</a><button className="plab-export" onClick={()=>setSources(false)}>Close</button></aside></div>}
 </PharmaLabShell>
}
