import { useEffect, useMemo, useRef, useState } from "react";
import { Box, CheckCircle2, Droplets, FlaskConical, Layers3, Pause, Play, RotateCcw, ScanLine, Sparkles } from "lucide-react";
import PharmaLabShell from "./components/PharmaLabShell.jsx";
import CharacterizationViewport from "./components/CharacterizationViewport.jsx";
import ScientificChart from "./components/ScientificChart.jsx";
import ExperimentControls from "./components/ExperimentControls.jsx";
import { makePreformulationData } from "./simulation/preformulationModel.js";
import "./pharmaLab.css";
import "./preformulation.css";

const compatibility = [
  ["Microcrystalline cellulose", "No change", "No change", "Compatible"],
  ["Lactose monohydrate", "Slight yellowing", "No significant change", "Monitor"],
  ["PVP K30", "No change", "No change", "Compatible"],
  ["Croscarmellose sodium", "No change", "No change", "Compatible"],
  ["Magnesium stearate", "Slight interaction", "Minor peak shift", "Monitor"],
];
const tabs = [[ScanLine,"Identity"],[Sparkles,"Solid State"],[FlaskConical,"Solubility"],[Droplets,"Particle Size"],[Layers3,"Compatibility"]];

export default function PreformulationPage(){
  const timer=useRef(null); const [query,setQuery]=useState(""); const [active,setActive]=useState("Solid State"); const [temperature,setTemperature]=useState(25); const [pH,setPH]=useState(7); const [particleSize,setParticleSize]=useState(62); const [polymorph,setPolymorph]=useState("Form I"); const [humidity,setHumidity]=useState(75); const [excipient,setExcipient]=useState("MCC"); const [rotation,setRotation]=useState(0); const [instrument,setInstrument]=useState("DSC"); const [running,setRunning]=useState(false); const [started,setStarted]=useState(false); const [speed,setSpeed]=useState(1); const [progress,setProgress]=useState(0); const [motion,setMotion]=useState(false); const [sources,setSources]=useState(false); const [mode,setMode]=useState("guided"); const [message,setMessage]=useState("Choose an instrument, verify conditions, then start the simulated characterization run.");
  const data=useMemo(()=>makePreformulationData({temperature,polymorph,particleSize,humidity,excipient}),[temperature,polymorph,particleSize,humidity,excipient]);
  useEffect(()=>{clearInterval(timer.current);if(running)timer.current=setInterval(()=>setProgress(value=>Math.min(100,value+speed)),160);return()=>clearInterval(timer.current)},[running,speed]);
  useEffect(()=>{if(progress>=100&&running){setRunning(false);setMessage(`${instrument} run complete. Trace and representative result are ready for interpretation.`)}},[progress,running,instrument]);
  const reset=()=>{setTemperature(25);setPH(7);setParticleSize(62);setPolymorph("Form I");setHumidity(75);setExcipient("MCC");setRotation(0);setProgress(0);setRunning(false);setStarted(false);setMessage("Conditions restored to the paracetamol teaching preset.")};
  const toggle=()=>{setStarted(true);setRunning(value=>!value);setMessage(running?"Run paused. Parameters remain locked in the current trace.":`${instrument} simulation running at ${speed}× speed.`)};
  const step=()=>{setStarted(true);setProgress(value=>Math.min(100,value+10));setMessage(`Advanced ${instrument} acquisition by one interval.`)};
  const selectInstrument=(name)=>{setInstrument(name);setProgress(0);setRunning(false);setStarted(false);setMessage(`${name} selected. The corresponding teaching trace is ready.`)};
  const aqueous=data.solubility.reduce((best,point)=>Math.abs(point.x-pH)<Math.abs(best.x-pH)?point:best).y;
  const monitor=data.risk>28;
  return <PharmaLabShell query={query} setQuery={setQuery} activeStage={3} onReset={reset} onSave={()=>setMessage("Characterization report saved locally.")} onSources={()=>setSources(true)} reducedMotion={motion} setReducedMotion={setMotion}>
    <main className="plab-preform">
      <header className="plab-page-title"><div><span className="plab-panel-kicker">STAGE 04 · PREFORMULATION</span><h1>API Characterization</h1><p>Paracetamol · solid-state, solution and excipient behavior</p></div><div className="plab-mode"><button className={mode==="guided"?"active":""} onClick={()=>setMode("guided")}>Guided</button><button className={mode==="free"?"active":""} onClick={()=>setMode("free")}>Free experiment</button></div></header>
      <div className="plab-preform-grid">
        <aside className="plab-preform-nav"><h2>Preformulation</h2><small>API characterization</small>{tabs.map(([Icon,name])=><button key={name} className={active===name?"active":""} onClick={()=>setActive(name)}><Icon/>{name}</button>)}<div className="plab-structure"><span>HO</span><svg viewBox="0 0 100 100"><path d="M22 35 48 20 75 35 75 65 48 80 22 65Z M48 20 48 5 M48 5 63 0 M75 65 91 75"/><text x="39" y="8">HN</text><text x="80" y="88">CH₃</text></svg><b>Paracetamol</b><small>C₈H₉NO₂ · 151.16 g/mol</small></div></aside>
        <section className="plab-characterization"><div className="plab-instrument-head"><span>Solid-State and Physical Characterization</span><b>{instrument} · {progress.toFixed(0)}%</b></div><CharacterizationViewport polymorph={polymorph} running={running&&!motion} rotation={rotation} instrument={instrument} humidity={humidity}/><div className="plab-rotation-control"><button onClick={()=>setRotation(value=>value-20)}><RotateCcw/>Rotate</button><input aria-label="Crystal rotation" type="range" min="-90" max="90" value={rotation} onChange={e=>setRotation(Number(e.target.value))}/><button onClick={()=>setRunning(value=>!value)}>{running?<Pause/>:<Play/>}{running?"Pause":"Animate"}</button></div></section>
        <aside className="plab-compat"><h2>Excipient Compatibility</h2><small>40 °C / 75% RH · 4 weeks · representative dataset</small><table><thead><tr><th>Excipient</th><th>Appearance</th><th>DSC</th><th>Assessment</th></tr></thead><tbody>{compatibility.map(row=><tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td><td>{row[2]}</td><td className={row[3]==="Compatible"?"pass":"watch"}>● {row[3]}</td></tr>)}</tbody></table><div className="plab-dvs"><div><small>Moisture uptake at 25 °C</small><strong>{data.dvs[8].y.toFixed(2)}% w/w</strong><span>at 80% RH · low hygroscopicity</span></div><ScientificChart data={data.dvs} xLabel="Relative humidity (% RH)" yLabel="Mass change (%)" label="Simulated DVS isotherm"/></div></aside>
      </div>
      <section className="plab-properties">{[["Aqueous solubility",`${aqueous.toFixed(2)} mg/mL`,`${temperature} °C · pH ${pH}`],["pKa","9.38","phenolic OH"],["LogP / LogD₇","0.49 / "+data.logD.toFixed(2),"octanol / water"],["Melting point",`${data.melt.toFixed(1)} °C`,polymorph],["Particle size",`D50 ${particleSize} µm`,`D10 18 · D90 ${Math.round(particleSize*2.39)} µm`],["Intrinsic dissolution",`${data.dissolution.toFixed(2)}`,"mg/cm²/min"]].map(([label,value,note])=><article key={label}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>)}</section>
      <section className="plab-preform-charts"><article><h3>pH–Solubility Profile</h3><ScientificChart data={data.solubility.map(point=>({...point,y:Math.log10(point.y)}))} xLabel="pH" yLabel="log₁₀ solubility" label="Calculated weak-acid pH solubility curve"/></article><article><h3>DSC Thermogram</h3><ScientificChart data={data.dsc} xLabel="Temperature (°C)" yLabel="Heat flow (mW)" color="#7dd3fc" label="Simulated DSC thermogram"/></article><article><h3>PXRD Pattern · Cu Kα</h3><ScientificChart data={data.pxrd} xLabel="2θ (°)" yLabel="Relative intensity" color="#22d3ee" label="Simulated powder X-ray diffraction pattern"/></article><article><h3>Particle Size Distribution</h3><ScientificChart data={data.psd} xLabel="Particle size (µm)" yLabel="Volume (%)" color="#67e8f9" label="Simulated laser diffraction particle distribution"/></article></section>
      <section className="plab-analysis"><div className="plab-analysis-buttons">{[["DSC",ScanLine],["pH Solubility",FlaskConical],["PXRD",Box],["DVS",Droplets]].map(([name,Icon])=><button className={instrument===name?"active":""} key={name} onClick={()=>selectInstrument(name)}><Icon/>{name}</button>)}</div><div className="plab-analysis-controls"><label>Temperature <input type="range" min="5" max="80" value={temperature} onChange={e=>setTemperature(Number(e.target.value))}/><output>{temperature} °C</output></label><label>pH <input type="range" min="1" max="12" step="0.5" value={pH} onChange={e=>setPH(Number(e.target.value))}/><output>{pH}</output></label><label>D50 <input type="range" min="10" max="250" value={particleSize} onChange={e=>setParticleSize(Number(e.target.value))}/><output>{particleSize} µm</output></label><label>Humidity <input type="range" min="0" max="95" value={humidity} onChange={e=>setHumidity(Number(e.target.value))}/><output>{humidity}% RH</output></label><select aria-label="Polymorph" value={polymorph} onChange={e=>setPolymorph(e.target.value)}><option>Form I</option><option>Form II</option><option>Amorphous</option></select><select aria-label="Excipient" value={excipient} onChange={e=>setExcipient(e.target.value)}><option>MCC</option><option>Lactose</option><option>PVP K30</option><option>Croscarmellose</option><option>Magnesium stearate</option></select></div><ExperimentControls running={running} started={started} onToggle={toggle} onStep={step} onReset={reset} speed={speed} onSpeedChange={setSpeed}/><p role="status">{message}</p></section>
      <section className={`plab-recommend ${monitor?"monitor":""}`}><CheckCircle2/><div><b>{monitor?"Compatibility monitoring advised":"Develop immediate-release 500 mg tablet"}</b><span>{monitor?`${excipient} risk index ${data.risk.toFixed(0)}/100 at selected conditions.`:"Suitable physical properties, low hygroscopicity and manageable particle-size distribution."}</span></div></section>
      <footer className="plab-educational-note">Calculated and simulated traces are representative teaching models, not lot-release or regulatory data.</footer>
    </main>
    {sources&&<div className="plab-drawer-backdrop" onClick={()=>setSources(false)}><aside className="plab-drawer" onClick={e=>e.stopPropagation()}><span className="plab-panel-kicker">PAGE 4 PROVENANCE</span><h2>Characterization sources</h2><p>Compound identity is referenced to PubChem CID 1983. Solid-state traces, DVS response, particle-size data and compatibility outcomes are explicitly representative educational simulations. The pH-solubility curve uses the Henderson–Hasselbalch weak-acid relationship.</p><a href="https://pubchem.ncbi.nlm.nih.gov/compound/1983" target="_blank" rel="noreferrer">Paracetamol · PubChem CID 1983</a><button className="plab-export" onClick={()=>setSources(false)}>Close source panel</button></aside></div>}
  </PharmaLabShell>;
}
