import { useEffect, useMemo, useRef, useState } from "react";
import { CheckCircle2, CircleStop, Cog, Layers3, PackageCheck, Pause, Play, RotateCcw, RotateCw, Waves } from "lucide-react";
import PharmaLabShell from "./components/PharmaLabShell.jsx";
import TabletLineViewport from "./components/TabletLineViewport.jsx";
import ScientificChart from "./components/ScientificChart.jsx";
import ExperimentControls from "./components/ExperimentControls.jsx";
import { defaultTabletFormula, formulaTotal, simulateTabletBatch, validateTabletFormula } from "./simulation/formulationModel.js";
import "./pharmaLab.css";
import "./tabletFormulation.css";

const steps=["Sieve","Granulate","Dry","Mill","Blend","Compress","Coat / Pack"];
const initialFormula=()=>defaultTabletFormula.map(item=>({...item}));

export default function TabletFormulationPage(){
 const timer=useRef(null);const [query,setQuery]=useState("");const [stage,setStage]=useState(5);const [formula,setFormula]=useState(initialFormula);const [targetWeight,setTargetWeight]=useState(650);const [turretSpeed,setTurretSpeed]=useState(35);const [force,setForce]=useState(12.5);const [fillDepth,setFillDepth]=useState(8.2);const [progress,setProgress]=useState(0);const [running,setRunning]=useState(false);const [started,setStarted]=useState(false);const [speed,setSpeed]=useState(1);const [motion,setMotion]=useState(false);const [sources,setSources]=useState(false);const [mode,setMode]=useState("guided");const [message,setMessage]=useState("Formula verified. Start the educational development batch.");
 const validation=useMemo(()=>validateTabletFormula(formula,targetWeight),[formula,targetWeight]);
 const result=useMemo(()=>{try{return simulateTabletBatch({targetWeight,turretSpeed,force,fillDepth,formula})}catch{return null}},[targetWeight,turretSpeed,force,fillDepth,formula]);
 useEffect(()=>{clearInterval(timer.current);if(running)timer.current=setInterval(()=>setProgress(value=>Math.min(100,value+speed*.8)),120);return()=>clearInterval(timer.current)},[running,speed]);
 useEffect(()=>{if(progress>=100&&running){setRunning(false);setMessage("Batch complete. Review in-process controls and quality assessment.")}},[progress,running]);
 const reset=()=>{setFormula(initialFormula());setTargetWeight(650);setTurretSpeed(35);setForce(12.5);setFillDepth(8.2);setProgress(0);setRunning(false);setStarted(false);setStage(5);setMessage("Default 650 mg immediate-release tablet preset restored.")};
 const toggle=()=>{if(!validation.valid){setMessage(validation.message);return}setStarted(true);setRunning(value=>!value);setMessage(running?"Compression paused safely.":"Compression batch running; CQAs recalculate from the selected process settings.")};
 const updateWeight=value=>{const next=Number(value);setTargetWeight(next);setFormula(items=>items.map(item=>item.id==="api"?{...item,mg:Math.max(0,next-(formulaTotal(items)-item.mg))}:item))};
 const pass=result&&Object.values(result.passes).every(Boolean);
 return <PharmaLabShell query={query} setQuery={setQuery} activeStage={4} onReset={reset} onSave={()=>setMessage("Formulation and process report saved locally.")} onSources={()=>setSources(true)} reducedMotion={motion} setReducedMotion={setMotion}>
  <main className="plab-tablet"><header className="plab-page-title"><div><span className="plab-panel-kicker">STAGE 05 · DOSAGE FORM</span><h1>Tablet Formulation</h1><p>Paracetamol 500 mg · immediate-release educational development batch</p></div><div className="plab-mode"><button className={mode==="guided"?"active":""} onClick={()=>setMode("guided")}>Guided</button><button className={mode==="free"?"active":""} onClick={()=>setMode("free")}>Free experiment</button></div></header>
   <div className="plab-tablet-grid"><aside className="plab-tablet-nav"><h2>Dosage Form</h2><small>Granules to tablets</small>{steps.map((name,index)=><button key={name} className={stage===index?"active":stage>index?"done":""} onClick={()=>setStage(index)}><span>{stage>index?"✓":index+1}</span>{name}</button>)}<div className="plab-tablet-identity"><div className="tablet-icon">500</div><b>Paracetamol</b><small>C₈H₉NO₂ · 151.16 g/mol</small></div></aside>
    <section className="plab-tablet-machine"><div className="plab-instrument-head"><span>From Granules to Tablets</span><b>{progress.toFixed(0)}% batch progress</b></div><TabletLineViewport stage={steps[stage]} running={running&&!motion} progress={progress}/><FormulaTable formula={formula} setFormula={setFormula} targetWeight={targetWeight} validation={validation}/></section>
    <aside className="plab-compression"><h2>Compression Process Controls</h2><Control icon={<RotateCw/>} label="Turret speed" value={turretSpeed} setValue={setTurretSpeed} min={10} max={60} step={1} unit="rpm"/><Control icon={<Layers3/>} label="Compression force" value={force} setValue={setForce} min={5} max={30} step={.5} unit="kN"/><Control icon={<Cog/>} label="Fill depth" value={fillDepth} setValue={setFillDepth} min={5} max={12} step={.1} unit="mm"/><Control icon={<PackageCheck/>} label="Target tablet weight" value={targetWeight} setValue={updateWeight} min={600} max={700} step={5} unit="mg"/><Control icon={<Waves/>} label="Hardness target" value={result?.hardnessMean.toFixed(0)||0} readOnly unit="N"/><button className="plab-start-batch" onClick={toggle}>{running?<Pause/>:<Play/>}<span><b>{running?"Pause Batch":"Start Batch"}</b><small>Educational Development Batch</small></span></button><div className="plab-batch-actions"><button onClick={()=>{setRunning(false);setMessage("Batch stopped; partial results retained.")}}><CircleStop/>Stop</button><button onClick={toggle}><Pause/>{running?"Pause":"Resume"}</button><button onClick={reset}><RotateCcw/>Reset</button></div><ExperimentControls running={running} started={started} onToggle={toggle} onStep={()=>{if(!validation.valid)return setMessage(validation.message);setStarted(true);setProgress(value=>Math.min(100,value+10));setStage(value=>Math.min(6,value+(progress%20===0?1:0)))}} onReset={reset} speed={speed} onSpeedChange={setSpeed}/><p role="status" className={validation.valid?"valid":"invalid"}>{message}</p></aside>
   </div>
   <section className="plab-tablet-results"><MetricChart title="Tablet Weight" data={result?.weights.map((y,i)=>({x:i+1,y}))||[]} note={`Mean ${result?.weightMean.toFixed(1)} mg · RSD ${result?.weightRsd.toFixed(2)}%`}/><MetricChart title="Tablet Hardness" data={result?.hardness.map((y,i)=>({x:i+1,y}))||[]} note={`Mean ${result?.hardnessMean.toFixed(1)} N · RSD ${result?.hardnessRsd.toFixed(2)}%`}/><MetricChart title="Blend Uniformity" data={result?.blend.map((y,i)=>({x:i+1,y}))||[]} note={`Assay ${result?.assay.toFixed(1)}% · RSD ${result?((Math.max(...result.blend)-Math.min(...result.blend))/result.blend[0]*100).toFixed(2):0}%`}/>{[["Friability",result?`${result.friability.toFixed(2)}%`:"—","Target ≤ 1.0%",result?.passes.friability],["Disintegration",result?`${result.disintegration.toFixed(1)} min`:"—","Target ≤ 15 min",result?.passes.disintegration],["Tablet Thickness",result?`${result.thickness.toFixed(2)} mm`:"—","Target 4.0–4.8 mm",result?.passes.thickness]].map(([a,b,c,d])=><article className="plab-cqa" key={a}><h3>{a}</h3><strong>{b}</strong><span>{c}</span><b className={d?"pass":"fail"}>{d?"✓ Pass":"! Adjust"}</b></article>)}<article className="plab-quality"><h3>Quality Assessment</h3>{result&&Object.entries(result.passes).map(([key,value])=><span key={key} className={value?"pass":"fail"}>{value?"✓":"!"} {key}</span>)}<b>{pass?"OVERALL RESULT: PASS":"ADJUST PROCESS"}</b></article></section>
   <footer className="plab-educational-note">Representative educational process model · not for clinical, manufacturing, or batch-release use.</footer>
  </main>{sources&&<div className="plab-drawer-backdrop" onClick={()=>setSources(false)}><aside className="plab-drawer" onClick={e=>e.stopPropagation()}><span className="plab-panel-kicker">PAGE 5 PROVENANCE</span><h2>Formulation model</h2><p>Formula composition is calculated from entered component masses. Weight, hardness, friability, disintegration, thickness and blend results are explicitly representative teaching simulations coupled to force, speed, fill depth, target weight and formula.</p><a href="https://pubchem.ncbi.nlm.nih.gov/compound/1983" target="_blank" rel="noreferrer">Paracetamol identity · PubChem CID 1983</a><button className="plab-export" onClick={()=>setSources(false)}>Close source panel</button></aside></div>}
 </PharmaLabShell>
}

function FormulaTable({formula,setFormula,targetWeight,validation}){return <div className="plab-formula"><div><h3>Tablet Formula <small>per {targetWeight} mg tablet</small></h3><b className={validation.valid?"valid":"invalid"}>{validation.total.toFixed(1)} mg · {(validation.total/targetWeight*100).toFixed(2)}%</b></div><table><thead><tr><th>Component</th><th>Function</th><th>Amount (mg)</th><th>% w/w</th></tr></thead><tbody>{formula.map(item=><tr key={item.id}><td>{item.component}</td><td>{item.role}</td><td><input aria-label={`${item.component} amount`} type="number" min="0" step="1" value={item.mg} onChange={e=>setFormula(items=>items.map(row=>row.id===item.id?{...row,mg:Number(e.target.value)}:row))}/></td><td>{(item.mg/targetWeight*100).toFixed(2)}</td></tr>)}<tr><th>Total</th><th/><th>{validation.total.toFixed(1)}</th><th>{(validation.total/targetWeight*100).toFixed(2)}</th></tr></tbody></table></div>}
function Control({icon,label,value,setValue,min,max,step,unit,readOnly}){return <label className="plab-compression-control"><span>{icon}<b>{label}</b></span>{!readOnly&&<input type="range" min={min} max={max} step={step} value={value} onChange={e=>setValue(Number(e.target.value))}/>}<output>{value} {unit}</output></label>}
function MetricChart({title,data,note}){return <article className="plab-metric-chart"><h3>{title}</h3><small>{note}</small><ScientificChart data={data} xLabel="Sample number" yLabel={title} label={`${title} representative in-process results`}/></article>}
