import { useMemo, useState } from 'react';
import { Download, FileText, Ruler, Sparkles } from 'lucide-react';
import './proteinEnhancementCenter.css';

const presets = [
  ['1MBN', 'Myoglobin', '153 residues · heme protein'],
  ['1HHO', 'Hemoglobin', 'Oxygen transport · tetramer'],
  ['4INS', 'Insulin', 'Hormone · disulfide-rich'],
  ['1CRN', 'Crambin', 'Small α/β teaching structure'],
];

const downloadText = (name, content, type = 'text/plain') => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a'); link.href = url; link.download = name; link.click();
  URL.revokeObjectURL(url);
};

export default function ProteinEnhancementCenter({ data, selected, chooseResidue, modes, setModes, colorScheme, setColorScheme, viewer, onLoadStructure, onLoadPdbId, onClose, onNotice }) {
  const [tab, setTab] = useState('Explore');
  const [secondResidue, setSecondResidue] = useState(64);
  const [lessonStep, setLessonStep] = useState(0);
  const [lessonAnswer, setLessonAnswer] = useState('');
  const selectedResidue = data.residues.find(r => r.resi === selected) || data.residues[0];
  const otherResidue = data.residues.find(r => r.resi === Number(secondResidue)) || data.residues[1];
  const distance = useMemo(() => Math.sqrt((selectedResidue.x - otherResidue.x) ** 2 + (selectedResidue.y - otherResidue.y) ** 2 + (selectedResidue.z - otherResidue.z) ** 2), [selectedResidue, otherResidue]);
  const composition = useMemo(() => Object.entries(data.residues.reduce((acc, r) => { acc[r.letter] = (acc[r.letter] || 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1]), [data]);
  const exportCSV = () => downloadText('1MBN-residues.csv', `position,residue,x,y,z\n${data.residues.map(r => `${r.resi},${r.letter},${r.x.toFixed(3)},${r.y.toFixed(3)},${r.z.toFixed(3)}`).join('\n')}`, 'text/csv');
  const exportReport = () => downloadText('1MBN-protein-report.txt', `Protein Folding Studio report\n\nMyoglobin · PDB 1MBN\nResidues: ${data.residues.length}\nSelected residue: ${selectedResidue.resn} ${selectedResidue.resi}\nMeasured distance to ${otherResidue.resn} ${otherResidue.resi}: ${distance.toFixed(2)} Å\n\nThis report contains educational measurements from the bundled experimental structure.\n`);
  const lesson = [
    ['Find the heme pocket', 'Select residue H64 in the sequence or enter 64 below.', '64'],
    ['Compare two residues', 'Use the measurement tab to compare two Cα positions.', 'measure'],
    ['Test a hypothesis', 'Turn on Labels and identify the hydrophobic core annotation.', 'labels'],
  ][lessonStep];
  return <div className="ps-enhancement-center">
    <div className="ps-enhancement-tabs">{['Explore', 'Measure', 'Analyze', 'Learn', 'Export'].map(item => <button type="button" key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === 'Explore' && <div className="ps-tool-grid">
      <section><h3>Protein library</h3><p className="ps-tool-muted">Choose a real PDB structure or load a local coordinate file.</p><div className="ps-library-grid">{presets.map(([id, name, detail]) => <button type="button" key={id} className={data.metadata.id === id ? 'selected' : ''} onClick={() => id === '1MBN' ? fetch('/assets/proteins/1MBN.pdb').then(response=>response.text()).then(text=>onLoadStructure(text,'1MBN.pdb')).catch(error=>onNotice(error.message)) : onLoadPdbId?.(id)}><strong>{id}</strong><span>{name}</span><small>{detail}</small></button>)}</div><label className="ps-file-loader">Load PDB/mmCIF file<input type="file" accept=".pdb,.ent,.cif,.mmcif" onChange={async e => { const file=e.target.files?.[0]; if(!file)return; try { await onLoadStructure(await file.text(),file.name); } catch (error) { onNotice(error.message); } }}/></label></section>
      <section><h3>Display & chains</h3><label>Chain <select defaultValue={data.metadata.chains[0]}>{data.metadata.chains.map(chain=><option key={chain}>{chain} · coordinate chain</option>)}</select></label><label>Color by <select value={colorScheme} onChange={e => setColorScheme(e.target.value)}><option value="spectrum">Sequence rainbow</option><option value="chain">Chain</option><option value="element">Element / CPK</option><option value="secondary">Secondary structure</option><option value="residue">Residue</option><option value="hydrophobicity">Hydrophobicity</option><option value="bfactor">B-factor / uncertainty</option></select></label><label>Representation <select value={modes.Cartoon ? 'cartoon' : modes.Sticks ? 'sticks' : 'surface'} onChange={e => setModes(v => ({ ...v, Cartoon: e.target.value === 'cartoon', Sticks: e.target.value === 'sticks', Surface: e.target.value === 'surface' }))}><option value="cartoon">Cartoon</option><option value="sticks">Sticks + atoms</option><option value="surface">Surface</option></select></label><div className="ps-tool-checks">{[['Labels','Labels'],['Surface','Surface'],['Sticks','Sticks']].map(([key, label]) => <label key={key}><input type="checkbox" checked={!!modes[key]} onChange={() => setModes(v => ({ ...v, [key]: !v[key] }))}/>{label}</label>)}</div></section>
      <section><h3>Residue inspector</h3><div className="ps-inspector-card"><strong>{selectedResidue.resn} {selectedResidue.resi}</strong><span>Chain A · one-letter code {selectedResidue.letter}</span><span>Coordinates: {selectedResidue.x.toFixed(2)}, {selectedResidue.y.toFixed(2)}, {selectedResidue.z.toFixed(2)} Å</span><button type="button" onClick={() => chooseResidue(selectedResidue.resi === data.residues.length ? 1 : selectedResidue.resi + 1)}>Next residue →</button></div></section>
    </div>}
    {tab === 'Measure' && <div className="ps-tool-grid"><section><h3><Ruler size={16}/> Distance & geometry</h3><p className="ps-tool-muted">Educational Cα distance measurement from the experimental coordinates.</p><label>Residue 1 <select value={selectedResidue.resi} onChange={e => chooseResidue(Number(e.target.value))}>{data.residues.map(r => <option key={r.resi} value={r.resi}>{r.resn} {r.resi}</option>)}</select></label><label>Residue 2 <select value={secondResidue} onChange={e => setSecondResidue(Number(e.target.value))}>{data.residues.map(r => <option key={r.resi} value={r.resi}>{r.resn} {r.resi}</option>)}</select></label><div className="ps-measure-result"><strong>{distance.toFixed(2)} Å</strong><span>{selectedResidue.resn}{selectedResidue.resi} Cα ↔ {otherResidue.resn}{otherResidue.resi} Cα</span></div><button type="button" onClick={() => { chooseResidue(selectedResidue.resi); onNotice('Measurement endpoints highlighted in the viewport.'); }}>Highlight endpoints</button></section><section><h3>Structural comparison</h3><p className="ps-tool-muted">Compare a second structure when a compatible PDB is loaded.</p><div className="ps-compare-card"><span>Reference</span><strong>1MBN · Myoglobin</strong><span>Comparison target</span><select><option>None selected</option><option>Library structure (placeholder)</option><option>Upload structure (coming next)</option></select><button type="button" onClick={() => onNotice('Alignment view is ready for a second loaded structure.')}>Open alignment view</button></div></section></div>}
    {tab === 'Analyze' && <div className="ps-tool-grid"><section><h3>Sequence composition</h3><div className="ps-composition">{composition.slice(0, 10).map(([letter, count]) => <div key={letter}><span>{letter}</span><i style={{ width: `${(count / data.residues.length) * 100}%` }}/><b>{count}</b></div>)}</div><p className="ps-tool-muted">Hydrophobic, polar, acidic, basic, and special residue classes remain available in the sequence legend.</p></section><section><h3>Analysis overlays</h3>{['Hydrophobicity profile','Solvent exposure','Conservation score','B-factor / mobility','Electrostatic surface'].map(label => <label className="ps-analysis-row" key={label}><input type="checkbox" onChange={() => onNotice(`${label} overlay toggled for the teaching view.`)}/><span>{label}</span><small>overlay</small></label>)}<div className="ps-summary-stat"><strong>{data.interactions.hydrophobic.length + data.interactions.ionic.length}</strong><span>screened contacts</span></div></section></div>}
    {tab === 'Learn' && <div className="ps-lesson"><div className="ps-lesson-progress">{[0, 1, 2].map(i => <i className={i <= lessonStep ? 'done' : ''} key={i}/>)}</div><h3>Guided protein lesson</h3><strong>Step {lessonStep + 1}: {lesson[0]}</strong><p>{lesson[1]}</p>{lesson[2] === '64' && <button type="button" onClick={() => { chooseResidue(64); setLessonAnswer('correct'); }}>Go to H64</button>}{lesson[2] === 'measure' && <button type="button" onClick={() => setTab('Measure')}>Open measurement tool</button>}{lesson[2] === 'labels' && <button type="button" onClick={() => { setModes(v => ({ ...v, Labels: true })); setLessonAnswer('correct'); }}>Show labels</button>}{lessonAnswer && <p className="ps-lesson-feedback">Great—now connect the sequence evidence to the 3D structure.</p>}<div className="ps-lesson-nav"><button type="button" disabled={lessonStep === 0} onClick={() => setLessonStep(v => v - 1)}>Back</button><button type="button" disabled={lessonStep === 2} onClick={() => { setLessonStep(v => v + 1); setLessonAnswer(''); }}>Next challenge</button></div></div>}
    {tab === 'Export' && <div className="ps-tool-grid"><section><h3><Download size={16}/> Export data</h3><div className="ps-dialog-actions"><button type="button" onClick={() => viewer?.png ? onNotice('Use Tools → Export molecular viewport PNG for the annotated 3D image.') : onNotice('Wait for Mol*.')}>Annotated PNG guidance</button><button type="button" onClick={exportCSV}>Residue table CSV</button><a href="/assets/proteins/1MBN.pdb" download>Bundled 1MBN coordinates</a><button type="button" onClick={exportReport}><FileText size={15}/> Teaching report</button></div></section><section><h3>Shareable workspace</h3><p className="ps-tool-muted">The current residue, display preferences, and lesson context can be saved in a shareable session link.</p><button type="button" onClick={() => { navigator.clipboard?.writeText(`${location.origin}/#/visuals/bio/proteins?residue=${selectedResidue.resi}`); onNotice('Shareable residue link copied.'); }}>Copy residue link</button><p className="ps-tool-muted">No personal data is included.</p></section></div>}
    <footer className="ps-enhancement-footer"><Sparkles size={15}/> Enhanced teaching workspace · illustrative analyses are labelled and should not be treated as validated simulation results. <button type="button" onClick={onClose}>Done</button></footer>
  </div>;
}
