let positions, velocities, forces, n = 108, running = false, timer, temperature = 300, volume = 3.2, rate = .5, realGas = true, time = 0;
const seed = 41291;
let state = seed;
const random = () => ((state = Math.imul(1664525, state) + 1013904223 >>> 0) / 4294967296);
function gaussian(){const u=Math.max(random(),1e-9),v=random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function reset(){state=seed;time=0;positions=new Float32Array(n*3);velocities=new Float32Array(n*3);forces=new Float32Array(n*3);const side=Math.ceil(Math.cbrt(n));let k=0;for(let z=0;z<side&&k<n;z++)for(let y=0;y<side&&k<n;y++)for(let x=0;x<side&&k<n;x++,k++){positions[k*3]=(x+.25+.5*random())/side-.5;positions[k*3+1]=(y+.25+.5*random())/side-.5;positions[k*3+2]=(z+.25+.5*random())/side-.5;velocities[k*3]=gaussian();velocities[k*3+1]=gaussian();velocities[k*3+2]=gaussian()}rescale();computeForces();emit()}
function rescale(){let mean=[0,0,0];for(let i=0;i<n;i++)for(let a=0;a<3;a++)mean[a]+=velocities[i*3+a]/n;let sum=0;for(let i=0;i<n;i++)for(let a=0;a<3;a++){velocities[i*3+a]-=mean[a];sum+=velocities[i*3+a]**2}const target=Math.sqrt((3*n*temperature/300)/Math.max(sum,1e-9));for(let i=0;i<velocities.length;i++)velocities[i]*=target}
function computeForces(){forces.fill(0);if(!realGas)return;const box=Math.cbrt(volume/3.2),cut2=.42*.42;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){let dx=positions[j*3]-positions[i*3],dy=positions[j*3+1]-positions[i*3+1],dz=positions[j*3+2]-positions[i*3+2];for(const a of [[0,dx],[1,dy],[2,dz]])if(a[1]>.5*box){if(a[0]===0)dx-=box;if(a[0]===1)dy-=box;if(a[0]===2)dz-=box}else if(a[1]<-.5*box){if(a[0]===0)dx+=box;if(a[0]===1)dy+=box;if(a[0]===2)dz+=box}const r2=dx*dx+dy*dy+dz*dz;if(r2<cut2&&r2>.006){const sr2=.0144/r2,sr6=sr2**3,f=24*sr6*(2*sr6-1)/r2*.00035;for(const [a,d] of [[0,dx],[1,dy],[2,dz]]){forces[j*3+a]+=f*d;forces[i*3+a]-=f*d}}}}
function step(){const dt=.004*(.45+rate);const oldBox=Math.cbrt(volume/3.2);if(rate>0)volume=Math.max(1.2,volume-rate*.0007);const box=Math.cbrt(volume/3.2),scale=box/oldBox;for(let i=0;i<positions.length;i++){velocities[i]+=.5*forces[i]*dt;positions[i]=(positions[i]+velocities[i]*dt)*scale;while(positions[i]>.5*box)positions[i]-=box;while(positions[i]<-.5*box)positions[i]+=box}computeForces();for(let i=0;i<velocities.length;i++)velocities[i]+=.5*forces[i]*dt;if(Math.floor(time*10)%8===0)rescale();time+=.01;if(Math.floor(time*100)%3===0)emit()}
function emit(){let kinetic=0,speed=[];for(let i=0;i<n;i++){const v=Math.hypot(velocities[i*3],velocities[i*3+1],velocities[i*3+2]);kinetic+=v*v;speed.push(v*244)}const pressure=8.314462618*temperature/(volume*1e-4);postMessage({positions:Array.from(positions),speed,time,temperature,volume,pressure,kinetic,seed})}
function loop(){if(!running)return;for(let i=0;i<3;i++)step();timer=setTimeout(loop,16)}
onmessage=e=>{const m=e.data;if(m.type==='reset'){temperature=m.temperature;volume=m.volume;rate=m.rate;realGas=m.realGas;running=false;clearTimeout(timer);reset()}if(m.type==='params'){temperature=m.temperature;rate=m.rate;realGas=m.realGas;if(!running)rescale();emit()}if(m.type==='run'&&!running){running=true;loop()}if(m.type==='pause'){running=false;clearTimeout(timer)}};

