import { useEffect, useRef } from 'react';
import * as T from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

export default function MolecularDynamicsScene({ frame, running }) {
  const host = useRef(null), live = useRef(null);
  useEffect(()=>{const node=host.current;const renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor(0x071522,0);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Interactive three-dimensional argon molecular dynamics chamber. Drag to rotate and scroll to zoom.');node.appendChild(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(39,1,.1,50);camera.position.set(2.7,1.5,3.7);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=2.5;controls.maxDistance=8;scene.add(new T.HemisphereLight(0xbce8ff,0x07111d,2));const key=new T.DirectionalLight(0xffffff,3);key.position.set(3,5,4);scene.add(key);const group=new T.Group();scene.add(group);const box=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(2.3,2.1,2.3)),new T.LineBasicMaterial({color:0x9bc9ff,transparent:true,opacity:.65}));group.add(box);const glass=new T.Mesh(new T.BoxGeometry(2.31,2.11,2.31),new T.MeshPhysicalMaterial({color:0x6fa8e5,transparent:true,opacity:.045,roughness:.1,metalness:.05,side:T.DoubleSide,depthWrite:false}));group.add(glass);const geometry=new T.SphereGeometry(.055,18,14),material=new T.MeshPhysicalMaterial({color:0x2886ff,roughness:.18,metalness:.08,clearcoat:1,emissive:0x06275b});const atoms=new T.InstancedMesh(geometry,material,108),dummy=new T.Object3D();group.add(atoms);const resize=new ResizeObserver(()=>{const r=node.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()});resize.observe(node);let raf;const draw=()=>{raf=requestAnimationFrame(draw);controls.update();renderer.render(scene,camera)};draw();live.current={atoms,dummy,box,glass};return()=>{cancelAnimationFrame(raf);resize.disconnect();controls.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material)Array.isArray(o.material)?o.material.forEach(m=>m.dispose()):o.material.dispose()});renderer.dispose();renderer.forceContextLoss();node.replaceChildren();live.current=null}},[]);
  useEffect(()=>{const s=live.current;if(!s||!frame?.positions)return;const side=Math.cbrt(frame.volume/3.2);for(let i=0;i<108;i++){s.dummy.position.set(frame.positions[i*3]*2,frame.positions[i*3+1]*1.8,frame.positions[i*3+2]*2);s.dummy.scale.setScalar(.85+Math.min(1,(frame.speed?.[i]||0)/700)*.35);s.dummy.updateMatrix();s.atoms.setMatrixAt(i,s.dummy.matrix)}s.atoms.instanceMatrix.needsUpdate=true;s.box.scale.set(side,1,side);s.glass.scale.set(side,1,side)},[frame]);
  return <div className="pcs-webgl" ref={host} data-running={running} data-seed={frame?.seed||''}/>;
}
