import { useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Download, Eye, FlaskConical, Gauge, HelpCircle, Lightbulb, Play, RefreshCw, Save, ShieldCheck, TestTube2, Trophy } from 'lucide-react';
import { absorbance, linearRegression, spectrum, standards, transmittance, unknownFromAbsorbance } from './beerLambertModel.js';
import { SciencePlot } from '../../components/science/SciencePlot.jsx';
import './BeerLambertLab.css';

const STEPS=[['home','Home'],['prepare','Prepare standards'],['measure','Measure absorbance'],['scan','Wavelength scan'],['calibration','Calibration curve'],['unknown','Unknown analysis'],['report','Report']];
const getStep=()=>Math.max(0,STEPS.findIndex(([id])=>id===new URLSearchParams(location.search).get('screen')));
const sci=(v,d=2)=>`${(v/10**Math.floor(Math.log10(Math.abs(v)||1))).toFixed(d)} × 10${String(Math.floor(Math.log10(Math.abs(v)||1))).replace('-','⁻')}`;

function Plot({type='calibration',fit,rows=[],unknown,revealed=true}){
  const points = type==='spectrum'
    ? Array.from({length:176},(_,i)=>({x:400+i*2,y:spectrum(400+i*2)}))
    : rows.map((row)=>({x:row.concentration,y:row.absorbance}));
  const xmax = Math.max(...points.map((point)=>point.x), unknown?.x || 0, type==='spectrum' ? 750 : 8e-5);
  const amax = Math.max(1, ...points.map((point)=>point.y), unknown?.y || 0);
  const peak = type==='spectrum' ? points.reduce((best,point)=>point.y>best.y?point:best, points[0]) : null;
  const series = [
    { label: type==='spectrum' ? 'Absorbance' : 'Standards', data: points, color: '#0866f2', points: type!=='spectrum', fill: type==='spectrum', fillcolor: 'rgba(8,102,242,0.16)', smooth: type==='spectrum', hover: type==='spectrum' ? 'λ = %{x:.0f} nm<br>A = %{y:.3f}<extra></extra>' : 'c = %{x:.2e} mol L⁻¹<br>A = %{y:.3f}<extra></extra>', markerSize: 9 },
    fit && type!=='spectrum' ? { label: 'Linear fit', data: [{x:0,y:fit.intercept},{x:xmax,y:fit.intercept+fit.slope*xmax}], color: '#e3a008', hover: 'Fit A = %{y:.3f}<extra></extra>' } : null,
    unknown ? { label: 'Unknown', data: [unknown], color: '#d9486f', points: true, mode: 'markers', hideLine: true, markerSize: 12, hover: 'Unknown<br>c = %{x:.2e} mol L⁻¹<br>A = %{y:.3f}<extra></extra>' } : null,
  ].filter(Boolean);
  const shapes = type==='spectrum'
    ? [{ type: 'line', x0: 620, x1: 620, y0: 0, y1: 1, yref: 'paper', line: { color: '#d48b00', width: 1.5, dash: 'dot' } }]
    : unknown
      ? [
          { type: 'line', x0: 0, x1: unknown.x, y0: unknown.y, y1: unknown.y, line: { color: '#d9486f', width: 1, dash: 'dot' } },
          { type: 'line', x0: unknown.x, x1: unknown.x, y0: 0, y1: unknown.y, line: { color: '#d9486f', width: 1, dash: 'dot' } },
        ]
      : [];
  const annotations = type==='spectrum' && peak
    ? [{ x: peak.x, y: peak.y, text: `λmax ${peak.x.toFixed(0)} nm`, showarrow: true, arrowhead: 0, ay: -28, ax: 36 }]
    : unknown
      ? [{ x: unknown.x, y: unknown.y, text: 'U-17', showarrow: true, arrowhead: 0, ay: -22, ax: 18 }]
      : [];
  if (type==='spectrum' && !revealed) {
    return <div className="bl-empty-scan"><div><strong>No spectrum yet</strong>Run the scan to collect 176 absorbance points from 400–750 nm.</div></div>;
  }
  return (
    <div className="bl-scope">
      <div className="bl-scope-bar">
        <span>{type==='spectrum' ? 'UV–Vis · single beam' : 'Calibration · least squares'}</span>
        <b>{type==='spectrum' ? 'λmax 620 nm' : fit ? `R² = ${fit.r2.toFixed(4)}` : 'A vs c'}</b>
      </div>
      <SciencePlot
        theme="lab"
        title={type==='spectrum' ? 'Absorption spectrum' : fit ? `A = ${fit.slope.toExponential(2)} c + ${fit.intercept.toFixed(3)}` : 'Calibration curve'}
        series={series}
        xLabel={type==='spectrum' ? 'Wavelength (nm)' : 'Concentration (mol L⁻¹)'}
        yLabel="Absorbance"
        xDomain={type==='spectrum' ? [400, 750] : [0, Math.max(8e-5, xmax * 1.05)]}
        yDomain={[0, amax * 1.08]}
        xTickFormat={type==='spectrum' ? '.0f' : '.1e'}
        yTickFormat=".2f"
        shapes={shapes}
        annotations={annotations}
        height={340}
      />
    </div>
  );
}
function Instrument({reading=.412,label='S3'}){return <div className="bl-instrument"><div className="lid"/><div className="slot"><div className="cuvette"><i style={{height:`${Math.min(90,20+reading*70)}%`}}/></div></div><div className="display"><small>λ　620 nm</small><b>A = {reading.toFixed(3)}</b><span>{label}</span></div><strong>UV–Vis Spectrophotometer</strong></div>}
function Panel({title,children,className=''}){return <section className={`bl-panel ${className}`}><h2>{title}</h2>{children}</section>}
function Header({step,go,reset}){return <><header className="bl-head"><button onClick={()=>go(Math.max(0,step-1))} aria-label="Previous screen"><ArrowLeft/></button><span>Virtual Labs　/　Instrumental Analysis</span><b>Beer–Lambert Laboratory</b><em>{step+1} of 7</em><div className="bl-dots">{STEPS.map((_,i)=><i className={i<=step?'done':''} key={i}/>)}</div><button><HelpCircle/> Help</button><button onClick={reset}><RefreshCw/> Reset</button></header><div className="bl-mobile-steps">{STEPS.map(([id,name],i)=><button key={id} className={i===step?'active':''} onClick={()=>go(i)}>{i+1}<span>{name}</span></button>)}</div></>}
function Footer({step,go}){return <footer className="bl-foot"><button onClick={()=>go(step-1)} disabled={!step}><ArrowLeft/> Previous</button><span/><button className="primary" onClick={()=>go(Math.min(6,step+1))}>{step===6?'Complete Lab':'Continue'} <ChevronRight/></button></footer>}

function Home({go}){return <main className="bl-home"><Panel title="Beer–Lambert Laboratory" className="intro"><p className="kicker">UV–Visible Spectrophotometry</p><p className="lead">Measure light absorption. Build a calibration curve. Determine an unknown.</p><div className="law">A = εbc</div><dl><dt>A</dt><dd>absorbance</dd><dt>ε</dt><dd>molar absorptivity</dd><dt>b</dt><dd>path length</dd><dt>c</dt><dd>concentration</dd></dl><button className="primary" onClick={()=>go(1)}><FlaskConical/> Start Experiment <ChevronRight/></button></Panel><section className="bl-hero"><Instrument reading={0}/><div className="bl-cuvettes">{standards().map(r=><i key={r.id} style={{'--fill':`${20+r.absorbance*75}%`}}><span>{r.id}</span></i>)}</div></section><div className="bl-mode-cards">{['Beer–Lambert Fundamentals','Unknown Concentration','Wavelength Scan','Assay Analysis'].map((x,i)=><button key={x} onClick={()=>go(i===2?3:i===1?5:1)}><TestTube2/><b>{x}</b><small>{['Build a calibration curve.','Determine a sample concentration.','Identify λmax.','Validate analytical results.'][i]}</small><ChevronRight/></button>)}</div></main>}
function Prepare({selected,setSelected,pipette,setPipette,prepared,setPrepared}){const target=[0,2,4,6,8][selected]*1e-5,required=target/1e-3*100;return <main className="bl-three"><Panel title="Prepare Standards" className="instructions"><p>Prepare CuSO₄ standards from 1.00 × 10⁻³ mol L⁻¹ stock.</p>{['Select a flask','Set pipette volume','Transfer stock','Dilute to the mark','Mix thoroughly'].map((x,i)=><div className={Math.abs(pipette-required)<.01&&i===1?'active':''} key={x}><b>{i+1}</b><span><strong>{x}</strong><small>{['Choose volumetric flask 1–5.','Set the required V₁.','Transfer the stock solution.','Add water to 100.0 mL.','Stopper and invert.'][i]}</small></span></div>)}</Panel><section className="bl-bench"><div className="stock">CuSO₄<small>1.00 × 10⁻³ M</small></div><div className="pipette" style={{'--amount':`${pipette/8*100}%`}}>{pipette.toFixed(2)} mL</div><div className="flasks">{[0,1,2,3,4].map(i=><button className={selected===i?'selected':''} key={i} onClick={()=>setSelected(i)}><i/><span>{i+1}</span></button>)}</div></section><Panel title="Calculation and Validation"><label>Selected flask<select value={selected} onChange={e=>setSelected(+e.target.value)}>{[1,2,3,4,5].map((x,i)=><option key={x} value={i}>Standard {x}</option>)}</select></label><div className="law small">C₁V₁ = C₂V₂</div><label>Required stock volume<input type="number" step=".1" value={pipette} onChange={e=>setPipette(+e.target.value)}/> mL</label><p className={Math.abs(pipette-required)<.01?'valid':'notice'}>{Math.abs(pipette-required)<.01?<><Check/> Calculation valid</>:`Set ${required.toFixed(2)} mL`}</p><button className="primary" disabled={Math.abs(pipette-required)>=.01} onClick={()=>setPrepared(p=>p|1<<selected)}>Add standard</button><p>{[0,1,2,3,4].map(i=><span className={prepared&1<<i?'ready':''} key={i}>S{i+1} {prepared&1<<i?'✓':'○'}　</span>)}</p></Panel></main>}
function Measure({sample,setSample,wavelength,setWavelength,pathLength,setPathLength,measurements,setMeasurements}){const rows=standards(pathLength),row=rows[sample],value=absorbance(row.concentration,pathLength)+(row.absorbance-absorbance(row.concentration,1));return <main className="bl-three"><Panel title="Measure Absorbance" className="instructions"><p>Blank the instrument, insert a standard, close the lid and record absorbance.</p>{['Blank instrument','Insert standard','Close lid','Measure absorbance'].map((x,i)=><div key={x}><b>{i+1}</b><span><strong>{x}</strong><small>Follow clean cuvette technique.</small></span></div>)}<label>Select sample<select value={sample} onChange={e=>setSample(+e.target.value)}>{rows.map((r,i)=><option value={i} key={r.id}>{r.id}</option>)}</select></label></Panel><section className="bl-bench instrument-bench"><Instrument reading={value} label={row.id}/><div className="bl-cuvettes">{rows.map((r,i)=><button className={sample===i?'selected':''} key={r.id} onClick={()=>setSample(i)}><i style={{'--fill':`${20+r.absorbance*75}%`}}/><span>{r.id}</span></button>)}</div></section><Panel title="Live Measurement"><label>Wavelength<input type="number" min="400" max="750" value={wavelength} onChange={e=>setWavelength(+e.target.value)}/> nm</label><div className="big-reading">A = {value.toFixed(3)}<small>T = {transmittance(value).toFixed(1)}%</small></div><label>Path length<input type="number" min=".1" max="5" step=".1" value={pathLength} onChange={e=>setPathLength(+e.target.value)}/> cm</label><button className="primary" onClick={()=>setMeasurements(m=>({...m,[row.id]:value}))}><Play/> Measure</button><table><tbody>{rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{measurements[r.id]?.toFixed(3)||'—'}</td></tr>)}</tbody></table></Panel></main>}
function Scan({scan,setScan}){return <main className="bl-three bl-scan"><Panel title="Wavelength Scan" className="instructions"><p>Record the absorption spectrum from 400 to 750 nm.</p><label>Sample<select><option>Copper(II) sulfate · S5</option></select></label><label>Start<input value="400" readOnly/> nm</label><label>End<input value="750" readOnly/> nm</label><button className="primary" onClick={()=>setScan(true)}><Play/> Run scan</button>{scan&&<p className="valid"><Check/> Scan complete · 176 points</p>}</Panel><Panel title="UV–Vis Absorption Spectrum" className="wide"><Plot type="spectrum" rows={[]} revealed={scan}/><div className="light-path"><span>White light</span><i/><div className="scan-cuvette"/><i/><span>Transmitted blue light</span></div></Panel><Panel title="Peak Analysis"><div className="big-reading">λmax = 620 nm<small>Amax = 0.811</small></div><p className="notice"><Lightbulb/> The solution appears blue because red–orange light is absorbed most strongly.</p></Panel></main>}
function Calibration({rows,setRows}){
  const used=rows.filter(r=>r.included!==false);
  const fit=linearRegression(used);
  const residuals=used.map((row)=>({x:row.concentration,y:row.absorbance-(fit.slope*row.concentration+fit.intercept)}));
  const span=Math.max(0.01, ...residuals.map((point)=>Math.abs(point.y)));
  return <main className="bl-three bl-cal"><Panel title="Standard Data"><table><thead><tr><th/><th>ID</th><th>c / mol L⁻¹</th><th>A</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td><input type="checkbox" checked={r.included!==false} onChange={()=>setRows(q=>q.map((x,j)=>j===i?{...x,included:x.included===false}:x))}/></td><td>{r.id}</td><td>{r.concentration.toExponential(1)}</td><td>{r.absorbance.toFixed(3)}</td></tr>)}</tbody></table></Panel><Panel title="Calibration Curve" className="wide"><Plot rows={used} fit={fit}/><h3>Residual Plot</h3><div className="bl-scope bl-residual"><SciencePlot theme="lab" series={[{label:'Residual',data:residuals,color:'#0866f2',points:true,mode:'markers',markerSize:9,hover:'c = %{x:.2e}<br>ΔA = %{y:.4f}<extra></extra>'}]} xLabel="Concentration (mol L⁻¹)" yLabel="A − fit" xDomain={[0,8e-5]} yDomain={[-span*1.4,span*1.4]} xTickFormat=".1e" yTickFormat=".3f" shapes={[{type:'line',x0:0,x1:8e-5,y0:0,y1:0,line:{color:'#d48b00',width:1.2}}]} height={168} legend={false}/></div></Panel><Panel title="Fit Quality"><p className="valid"><Check/> Excellent linearity</p>{[['R²',fit.r2.toFixed(4)],['Slope εb',fit.slope.toExponential(2)],['Intercept',fit.intercept.toFixed(3)],['Linear range','0–8.0 × 10⁻⁵ M']].map(([a,b])=><div className="metric" key={a}><span>{a}</span><b>{b}</b></div>)}<p className="notice">For b = 1.00 cm, slope = εb.</p></Panel></main>}
function Unknown({rows,dilution,setDilution,accepted,setAccepted}){const fit=linearRegression(rows),reading=.533,result=unknownFromAbsorbance(reading,fit,dilution);return <main className="bl-three"><Panel title="Determine Unknown Concentration" className="instructions"><div className="unknown-bottle">Unknown<br/>U-17</div><button><TestTube2/> Insert unknown</button><p><Check/> Blank verified</p><p><Check/> Calibration loaded</p><p><Check/> Unknown measured</p><table><tbody>{[.533,.529,.536].map((x,i)=><tr key={i}><td>{i+1}</td><td>{x.toFixed(3)}</td></tr>)}</tbody></table></Panel><Panel title="Sample Measurement" className="wide"><Instrument reading={reading} label="U-17"/><h3>Calibration Curve with Unknown</h3><Plot rows={rows} fit={fit} unknown={{x:result.diluted,y:reading}}/></Panel><Panel title="Unknown Result"><p className="valid"><Check/> Within calibration range</p>{[['Diluted concentration',result.diluted.toExponential(2)],['Mean absorbance',reading.toFixed(3)],['Original concentration',result.original.toExponential(2)]].map(([a,b])=><div className="metric" key={a}><span>{a}</span><b>{b}</b></div>)}<label>Dilution factor<input type="number" min="1" max="100" value={dilution} onChange={e=>setDilution(+e.target.value)}/></label><div className="law small">c = (A − b) / m</div><button className="primary" onClick={()=>setAccepted(true)}><Check/> {accepted?'Result accepted':'Accept result'}</button></Panel></main>}
function Report({rows,reset}){const [answers,setAnswers]=useState({}),fit=linearRegression(rows),result=unknownFromAbsorbance(.533,fit,10),score=[answers.q1==='direct',answers.q2==='blank',answers.q3==='sensitivity'].filter(Boolean).length;const download=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([`slope,intercept,r2,unknown\n${fit.slope},${fit.intercept},${fit.r2},${result.original}`],{type:'text/csv'}));a.href=url;a.download='beer-lambert-results.csv';a.click();URL.revokeObjectURL(url)};return <main className="bl-report"><Panel title="Experiment complete"><Trophy className="trophy"/><div className="completion">100%</div>{['Standards prepared','Instrument blanked','Spectrum scanned','Calibration validated','Unknown determined'].map(x=><p key={x}><Check/> {x}</p>)}</Panel><Panel title="Digital Lab Notebook" className="wide"><div className="notebook-tabs"><button>Results</button><button>Observations</button><button>Calculations</button><button>Conclusion</button></div><table><tbody>{[['λmax','620 nm'],['Calibration',`A = ${fit.slope.toExponential(2)}c + ${fit.intercept.toFixed(3)}`],['R²',fit.r2.toFixed(4)],['Unknown absorbance','0.533'],['Original concentration',result.original.toExponential(2)]].map(([a,b])=><tr key={a}><td>{a}</td><td>{b}</td></tr>)}</tbody></table><textarea defaultValue="The unknown was pale blue and clear. Measurements were stable and reproducible. The calibration remained linear across the validated range."/><p className="valid"><Check/> The concentration of U-17 was determined from the validated calibration.</p><button onClick={download}><Download/> Download CSV</button><button onClick={()=>print()}><Download/> Export PDF</button></Panel><Panel title="Knowledge Check"><p>1. Absorbance and concentration are:</p>{[['direct','Directly proportional'],['inverse','Inversely proportional']].map(([v,x])=><label key={v}><input type="radio" name="q1" checked={answers.q1===v} onChange={()=>setAnswers(a=>({...a,q1:v}))}/>{x}</label>)}<p>2. A blank corrects:</p><label><input type="radio" checked={answers.q2==='blank'} onChange={()=>setAnswers(a=>({...a,q2:'blank'}))}/> Background absorption</label><p>3. λmax gives:</p><label><input type="radio" checked={answers.q3==='sensitivity'} onChange={()=>setAnswers(a=>({...a,q3:'sensitivity'}))}/> Maximum sensitivity</label><div className={score===3?'valid':'notice'}>{score} / 3 correct</div><button onClick={reset}><RefreshCw/> Restart</button></Panel></main>}

export default function BeerLambertLab(){const [step,setStep]=useState(getStep),[selected,setSelected]=useState(2),[pipette,setPipette]=useState(4),[prepared,setPrepared]=useState(0),[sample,setSample]=useState(3),[wavelength,setWavelength]=useState(620),[pathLength,setPathLength]=useState(1),[measurements,setMeasurements]=useState({S1:.102,S2:.207}),[scan,setScan]=useState(false),[rows,setRows]=useState(()=>standards()),[dilution,setDilution]=useState(10),[accepted,setAccepted]=useState(false);const go=i=>{i=Math.max(0,Math.min(6,i));setStep(i);const u=new URL(location.href);u.searchParams.set('screen',STEPS[i][0]);history.replaceState({},'',u);scrollTo(0,0)};const reset=()=>{setSelected(2);setPipette(4);setPrepared(0);setSample(3);setWavelength(620);setPathLength(1);setMeasurements({});setScan(false);setRows(standards());setDilution(10);setAccepted(false);go(0)};return <div className="bl-app"><Header step={step} go={go} reset={reset}/>{step===0&&<Home go={go}/>} {step===1&&<Prepare {...{selected,setSelected,pipette,setPipette,prepared,setPrepared}}/>} {step===2&&<Measure {...{sample,setSample,wavelength,setWavelength,pathLength,setPathLength,measurements,setMeasurements}}/>} {step===3&&<Scan {...{scan,setScan}}/>} {step===4&&<Calibration {...{rows,setRows}}/>} {step===5&&<Unknown {...{rows,dilution,setDilution,accepted,setAccepted}}/>} {step===6&&<Report rows={rows} reset={reset}/>}<Footer step={step} go={go}/></div>}
