import { useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Download, Droplets, FlaskConical, HelpCircle, Pause, Play, RefreshCw, Save, ShieldCheck, Snowflake, Thermometer, Trophy } from 'lucide-react';
import { ethanolDistillate, fractionalRun, recrystallisation, reportSummary, steamRun } from './distillationModel.js';
import './DistillationCrystallisationLab.css';

const STEPS = [['home','Overview'],['setup','Configure mixture & apparatus'],['fractional','Run fractional distillation'],['steam','Steam distillation'],['crystals','Recrystallisation & purity'],['report','Lab report']];
const initialStep = () => Math.max(0, STEPS.findIndex(([id]) => id === new URLSearchParams(location.search).get('screen')));
const Panel = ({ title, children, className = '' }) => <section className={`dc-panel ${className}`}><h2>{title}</h2>{children}</section>;
const Metric = ({ label, value, good = false }) => <div className="dc-metric"><span>{label}</span><b className={good ? 'good' : ''}>{value}</b></div>;

function Header({ step, go, reset }) {
  return <header className="dc-head"><button onClick={() => go(step - 1)}><ArrowLeft /></button><span>Virtual Labs　/　Organic Chemistry</span><b>{STEPS[step][1]}　 {step + 1} of 6</b><div>{STEPS.map((_, i) => <i className={i <= step ? 'done' : ''} key={i} />)}</div><button><HelpCircle /> Help</button><button onClick={reset}><RefreshCw /> Reset</button></header>;
}
function Footer({ step, go }) {
  return <footer className="dc-foot"><button onClick={() => go(step - 1)} disabled={!step}><ArrowLeft /> Previous</button><button className="primary" onClick={() => go(step + 1)}>{step === 5 ? 'Complete Lab' : 'Continue'} <ChevronRight /></button></footer>;
}

function DistillationRig({ kind = 'fractional', active = false, volume = 38 }) {
  return <div className={`dc-rig ${kind}`} role="img" aria-label={`${kind} distillation apparatus`}>
    <div className="stand" /><div className="mantle"><span>{active ? '42%' : '78 °C'}</span></div><div className="flask"><i /><em>{kind === 'steam' ? 'Cloves' : 'Binary mixture'}</em></div>
    {kind === 'steam' && <div className="generator"><i /><span>Steam generator</span></div>}
    <div className="column"><i /><i /><i /><span>{kind === 'steam' ? 'Vapour path' : 'Vigreux column'}</span></div><div className="thermometer"><i /><span>{kind === 'steam' ? '98.6 °C' : active ? '78.4 °C' : 'Thermometer'}</span></div>
    <div className="condenser"><i /><i /><span>Liebig condenser</span></div><div className="receiver"><i style={{height:`${Math.min(76, volume)}%`}} /><span>{volume.toFixed ? volume.toFixed(0) : volume} mL</span></div>
    <div className="water in">Water in</div><div className="water out">Water out</div>
  </div>;
}
function CrystalSequence() {
  return <div className="dc-sequence">{[['1','Hot solution'],['2','Hot gravity filtration'],['3','Slow cooling'],['4','Ice bath'],['5','Vacuum filtration']].map(([n,x]) => <div key={n}><b>{n}</b><div className={`scene s${n}`}><i /><i /><i /></div><span>{x}</span></div>)}</div>;
}
function Curve({ kind = 'fractional', marker = 38 }) {
  const points = Array.from({ length: 51 }, (_, i) => { const v = i * 2; const p = kind === 'fractional' ? ethanolDistillate(v) : steamRun(v / 2.2); return { x: v, y: kind === 'fractional' ? p.temperature : p.oilMass }; });
  const poly = points.map(p => `${48 + p.x * 5.4},${kind === 'fractional' ? 245 - (p.y - 60) * 4.5 : 245 - p.y * 65}`).join(' ');
  return <svg className="dc-chart" viewBox="0 0 640 280" role="img" aria-label={`${kind} results chart`}><line x1="48" x2="600" y1="245" y2="245"/><line x1="48" x2="48" y1="25" y2="245"/><polyline points={poly}/><line className="marker" x1={48 + marker * 5.4} x2={48 + marker * 5.4} y1="25" y2="245"/><text x="250" y="273">{kind === 'fractional' ? 'Distillate volume (mL)' : 'Time / distillate progress'}</text></svg>;
}

function Home({ go }) {
  return <main className="dc-home"><Panel title="Distillation & Crystallisation Laboratory" className="intro"><p className="kicker"><FlaskConical /> Organic Chemistry</p><p className="lead">Separate volatile liquids. Recover steam-sensitive compounds. Purify solids by crystallisation.</p><div className="dc-theory"><div><b>Vapour–Liquid Equilibrium (Raoult’s Law)</b><span>yᵢ = xᵢPᵢ° / P</span><small>The more volatile component enriches in the vapour, enabling separation.</small></div><Curve /></div><button className="primary" onClick={() => go(1)}><FlaskConical /> Start Experiment <ChevronRight /></button></Panel><section className="dc-hero"><DistillationRig /><div className="hazard"><ShieldCheck /> Flammable<br/><small>Keep away from ignition sources</small></div></section><div className="dc-cards">{['Fractional Distillation','Steam Distillation','Recrystallisation','Purity & Recovery'].map((x,i)=><button key={x} onClick={()=>go(Math.min(5,i+2))}><FlaskConical/><b>{x}</b><small>{['Separate components by volatility.','Recover steam-sensitive compounds.','Dissolve, cool and crystallise.','Analyze melting point and recovery.'][i]}</small><ChevronRight/></button>)}</div></main>;
}
function Setup({ method, setMethod, ethanol, setEthanol, validated, setValidated }) {
  return <main className="dc-three"><Panel title="Configure Mixture & Apparatus"><h3>1. Select Method</h3>{['Fractional Distillation','Steam Distillation','Recrystallisation'].map(x=><label className={method===x?'active':''} key={x}><input type="radio" checked={method===x} onChange={()=>setMethod(x)}/>{x}</label>)}<h3>2. Mixture Composition</h3><label>Ethanol / Water　<input aria-label="Ethanol mol percent" type="number" min="10" max="90" value={ethanol} onChange={e=>setEthanol(+e.target.value)}/> mol% ethanol</label><table><tbody><tr><td>Ethanol</td><td>{ethanol.toFixed(1)}%</td><td>78.37 °C</td></tr><tr><td>Water</td><td>{(100-ethanol).toFixed(1)}%</td><td>100.0 °C</td></tr></tbody></table><h3>3. Apparatus Parameters</h3><p>250 mL flask　300 mm Vigreux column</p><p>Anti-bumping granules: use</p></Panel><Panel title="Assembled Apparatus" className="dc-visual"><DistillationRig /><p>Drag components or validate the assembled joints.</p></Panel><Panel title="Setup Validation">{['Thermometer at sidearm','Flask ≤ 50% full','All joints secured','Cooling water lower → upper','Receiver vented','Compatible heat source'].map(x=><p className="check" key={x}><Check /> {x}</p>)}<p className={validated?'valid':'notice'}>{validated?<><Check/> Apparatus ready — all checks passed.</>:<>Validate before beginning heating.</>}</p><button className="primary" onClick={()=>setValidated(true)}><Check/> Validate setup</button><h3>Predicted Vapour–Liquid Equilibrium</h3><Curve marker={ethanol}/><div className="danger"><ShieldCheck/> Flammable vapours: use ventilation and avoid ignition.</div></Panel></main>;
}
function Fractional({ power, setPower, reflux, setReflux, running, setRunning, saved, setSaved }) {
  const run = useMemo(()=>fractionalRun(power,reflux),[power,reflux]);
  return <main className="dc-three"><Panel title="Run Fractional Distillation"><label>Heating mantle power <input aria-label="Heating mantle power" type="range" min="0" max="100" value={power} onChange={e=>setPower(+e.target.value)}/><b>{power}%</b></label><label>Reflux ratio <select value={reflux} onChange={e=>setReflux(+e.target.value)}>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x} : 1</option>)}</select></label><Metric label="Target takeoff rate" value="2 drops/s"/><Metric label="Coolant flow" value="120 mL/min"/><button onClick={()=>setRunning(x=>!x)}>{running?<Pause/>:<Play/>}{running?'Pause':'Start'}</button><h3>Fraction Collection Rules</h3><table><tbody><tr><td>Heads</td><td>&lt;77.5 °C</td></tr><tr><td>Main</td><td>77.5–82 °C</td></tr><tr><td>Transition</td><td>82–95 °C</td></tr><tr><td>Water-rich</td><td>&gt;95 °C</td></tr></tbody></table></Panel><Panel title="Live Fractional Distillation" className="dc-visual"><DistillationRig active={running} volume={run.volume}/><Curve marker={run.volume}/></Panel><Panel title="Run Status & Metrics"><Metric label="Pot temperature" value={`${run.potTemperature.toFixed(1)} °C`}/><Metric label="Head temperature" value={`${run.temperature.toFixed(1)} °C`}/><Metric label="Distillate volume" value={`${run.volume.toFixed(0)} mL`}/><Metric label="Distillate rate" value={`${run.dropRate.toFixed(1)} drops/s`}/><p className={running?'valid':'notice'}>{running?<><Check/> Stable main fraction collection</>:<>Start heating to collect distillate.</>}</p><h3>Separation Performance</h3><Metric label="Theoretical plates" value={run.theoreticalPlates.toFixed(1)}/><Metric label="Separation factor" value={run.separationFactor.toFixed(1)}/><button onClick={()=>setSaved(true)}><Save/> {saved?'Run saved':'Save run'}</button></Panel></main>;
}
function Steam({ steamRate, setSteamRate, minutes, setMinutes, separated, setSeparated }) {
  const run=steamRun(minutes,steamRate); return <main className="dc-three"><Panel title="Steam Distillation of Essential Oil"><Metric label="Cloves (ground)" value="20.0 g"/><Metric label="Water" value="150 mL"/><Metric label="Target head temperature" value="98.6 °C"/><label>Steam rate <input aria-label="Steam rate" type="range" min="0" max="5" step="0.1" value={steamRate} onChange={e=>setSteamRate(+e.target.value)}/><b>{steamRate.toFixed(1)} g/min</b></label><label>Run time <input aria-label="Steam run time" type="range" min="0" max="45" value={minutes} onChange={e=>setMinutes(+e.target.value)}/><b>{minutes.toFixed(0)} min</b></label><button onClick={()=>setMinutes(x=>Math.min(45,x+5))}><Play/> Collect more</button></Panel><Panel title="Co-distillation Apparatus" className="dc-visual"><DistillationRig kind="steam" active volume={run.distillateVolume}/><Curve kind="steam" marker={run.distillateVolume}/></Panel><Panel title="Run Status & Metrics"><Metric label="Distillate volume" value={`${run.distillateVolume.toFixed(0)} mL`}/><Metric label="Oil layer volume" value={`${run.oilVolume.toFixed(1)} mL`}/><Metric label="Estimated eugenol" value={`${run.oilMass.toFixed(2)} g`}/><Metric label="Recovery" value={`${run.recovery.toFixed(1)}%`} good/><p className="valid"><Check/> Head temperature stable at 98.6 °C.</p><h3>Separation & Purification</h3>{['Transfer to separatory funnel','Wash organic layer with brine','Dry over Na₂SO₄','Filter and collect oil'].map((x,i)=><p className="check" key={x}>{i===0||separated?<Check/>:<i/>}{x}</p>)}<button onClick={()=>setSeparated(true)}><Droplets/> Separate oil</button></Panel></main>;
}
function Crystals({ rate, setRate, seed, setSeed, analyzed, setAnalyzed }) {
  const result=recrystallisation({coolingRate:rate,seedingTemperature:seed}); return <main className="dc-crystals"><Panel title="Recrystallisation & Purity Analysis"><Metric label="Compound (crude)" value="Acetanilide　5.00 g"/><Metric label="Solvent" value="Water"/><h3>Solubility of acetanilide</h3><Metric label="At 100 °C" value="5.5 g / 100 mL"/><Metric label="At 10 °C" value="0.53 g / 100 mL"/><Metric label="Minimum hot solvent" value={`${result.minimumHotSolvent.toFixed(1)} mL`}/><h3>Workflow</h3>{['Dissolve near boiling','Hot gravity filter','Cool slowly','Ice bath','Vacuum filter','Wash cold','Dry to constant mass'].map((x,i)=><p key={x}>{i+1}. {x}</p>)}</Panel><Panel title="Experimental Sequence" className="wide"><CrystalSequence/><h2>Solubility Curve & Process Path</h2><Curve kind="crystals" marker={30}/></Panel><Panel title="Results & Purity Analysis"><Metric label="Recovered crystals" value={`${result.recovered.toFixed(2)} g`}/><Metric label="Theoretical recoverable" value={`${result.theoretical.toFixed(2)} g`}/><Metric label="Recovery" value={`${result.recovery.toFixed(1)}%`} good/><Metric label="Melting range (purified)" value="114.0–115.0 °C"/><Metric label="Purity" value={`${result.purity.toFixed(1)}%`} good/><p className="valid"><Check/> High-purity product obtained.</p><label>Cooling rate <input aria-label="Cooling rate" type="range" min="0.1" max="5" step="0.1" value={rate} onChange={e=>setRate(+e.target.value)}/><b>{rate.toFixed(1)} °C/min</b></label><label>Seeding temperature <input aria-label="Seeding temperature" type="range" min="0" max="60" value={seed} onChange={e=>setSeed(+e.target.value)}/><b>{seed} °C</b></label><button onClick={()=>setAnalyzed(true)}><Thermometer/> {analyzed?'Melting point analyzed':'Analyze melting point'}</button></Panel></main>;
}
function Report() {
  const [answers,setAnswers]=useState({}); const score=[answers.q1==='repeat',answers.q2==='pressure',answers.q3==='slow'].filter(Boolean).length; const {fractional,steam,crystals}=reportSummary();
  const csv=()=>{const text=`process,metric,value\nfractional,ethanol_mole_fraction,${fractional.ethanolMoleFraction.toFixed(3)}\nsteam,eugenol_recovery_percent,${steam.recovery.toFixed(1)}\nrecrystallisation,recovery_percent,${crystals.recovery.toFixed(1)}`;const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.href=u;a.download='distillation-crystallisation-results.csv';a.click();URL.revokeObjectURL(u)};
  return <main className="dc-report"><Panel title="Experiment Completion"><div className="completion">100%</div>{['Apparatus validated','Fractional distillation complete','Steam distillation complete','Recrystallisation complete','Purity and recovery analyzed'].map(x=><p className="check" key={x}><Check/>{x}</p>)}<Metric label="Total time" value="42:20"/><Metric label="Safety score" value="100%" good/></Panel><Panel title="Digital Lab Notebook" className="wide"><h3>Fractional Distillation (Ethanol/Water)</h3><Metric label="Main fraction volume" value={`${fractional.volume.toFixed(0)} mL`}/><Metric label="Ethanol composition" value={`${(fractional.ethanolMoleFraction*100).toFixed(1)} mol%`}/><h3>Steam Distillation (Cloves → Eugenol)</h3><Metric label="Mass recovered" value={`${steam.oilMass.toFixed(2)} g`}/><Metric label="Recovery" value={`${steam.recovery.toFixed(1)}%`}/><h3>Recrystallisation (Acetanilide)</h3><Metric label="Recovered mass" value={`${crystals.recovered.toFixed(2)} g`}/><Metric label="Purity" value={`${crystals.purity.toFixed(1)}%`}/><Curve marker={fractional.volume}/><p className="valid"><Check/> Results are consistent with effective application of all three separation methods.</p><button onClick={csv}><Download/> Download CSV</button><button onClick={()=>print()}><Download/> Export PDF</button></Panel><Panel title="Knowledge Check"><p>Why does a fractionating column improve separation?</p><label><input type="radio" checked={answers.q1==='repeat'} onChange={()=>setAnswers(a=>({...a,q1:'repeat'}))}/> Repeated vapour–liquid equilibration</label><p>Why does steam distillation lower effective boiling temperature?</p><label><input type="radio" checked={answers.q2==='pressure'} onChange={()=>setAnswers(a=>({...a,q2:'pressure'}))}/> Combined vapour pressures reach atmospheric pressure</label><p>Why does slow cooling increase purity?</p><label><input type="radio" checked={answers.q3==='slow'} onChange={()=>setAnswers(a=>({...a,q3:'slow'}))}/> Fewer, larger, purer crystals form</label><div className={score===3?'valid':'notice'}><Trophy/> Score: {score}/3</div><h3>Safety Status</h3><p><ShieldCheck/> Heat sources off</p><p><ShieldCheck/> System pressure vented</p></Panel></main>;
}

export default function DistillationCrystallisationLab(){
  const[step,setStep]=useState(initialStep),[method,setMethod]=useState('Fractional Distillation'),[ethanol,setEthanol]=useState(40),[validated,setValidated]=useState(false),[power,setPower]=useState(42),[reflux,setReflux]=useState(3),[running,setRunning]=useState(false),[saved,setSaved]=useState(false),[steamRate,setSteamRate]=useState(2.5),[minutes,setMinutes]=useState(36.33),[separated,setSeparated]=useState(false),[rate,setRate]=useState(1),[seed,setSeed]=useState(30),[analyzed,setAnalyzed]=useState(false);
  const go=n=>{n=Math.max(0,Math.min(5,n));setStep(n);const u=new URL(location.href);u.searchParams.set('screen',STEPS[n][0]);history.replaceState({},'',u);scrollTo(0,0)};
  const reset=()=>{setMethod('Fractional Distillation');setEthanol(40);setValidated(false);setPower(42);setReflux(3);setRunning(false);setSaved(false);setSteamRate(2.5);setMinutes(36.33);setSeparated(false);setRate(1);setSeed(30);setAnalyzed(false);go(0)};
  return <div className="dc-app"><Header step={step} go={go} reset={reset}/>{step===0&&<Home go={go}/>} {step===1&&<Setup {...{method,setMethod,ethanol,setEthanol,validated,setValidated}}/>} {step===2&&<Fractional {...{power,setPower,reflux,setReflux,running,setRunning,saved,setSaved}}/>} {step===3&&<Steam {...{steamRate,setSteamRate,minutes,setMinutes,separated,setSeparated}}/>} {step===4&&<Crystals {...{rate,setRate,seed,setSeed,analyzed,setAnalyzed}}/>} {step===5&&<Report/>}<Footer step={step} go={go}/></div>;
}
