import { useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Download, Droplets, Flame, FlaskConical, HelpCircle, Pause, Play, RefreshCw, Save, Settings, ShieldCheck, Sparkles, Trophy } from 'lucide-react';
import { ELEMENTS, SODIUM_INTENSITIES, STANDARD_CONCENTRATIONS, UNKNOWN_REPLICATES, dilutionVolume, flamePerformance, linearRegression, spectrum, unknownResult } from './flamePhotometryModel.js';
import './FlamePhotometryLab.css';

const STEPS = [['home','Overview'],['standards','Standards preparation'],['flame','Flame optimization'],['spectrum','Emission spectrum'],['calibration','Calibration & unknown'],['report','Report & assessment']];
const initialStep = () => Math.max(0, STEPS.findIndex(([id]) => id === new URLSearchParams(location.search).get('screen')));
const Panel = ({ title, children, className = '' }) => <section className={`fp-panel ${className}`}><h2>{title}</h2>{children}</section>;
const Metric = ({ label, value, good = false }) => <div className="fp-metric"><span>{label}</span><b className={good ? 'good' : ''}>{value}</b></div>;

function Header({ step, go, reset }) { return <header className="fp-head"><button onClick={()=>go(step-1)}><ArrowLeft/></button><span>Virtual Labs　/　Instrumental Analysis</span><b>Flame Photometry Laboratory　 {step+1} of 6</b><div>{STEPS.map((_,i)=><i className={i<=step?'done':''} key={i}/>)}</div><button><HelpCircle/> Help</button><button onClick={reset}><RefreshCw/> Reset</button></header>; }
function Footer({ step, go }) { return <footer className="fp-foot"><button onClick={()=>go(step-1)} disabled={!step}><ArrowLeft/> Previous</button><button className="primary" onClick={()=>go(step+1)}>{step===5?'Complete Lab':'Continue'} <ChevronRight/></button></footer>; }

function Instrument({ lit=true, element='Na', sample='Sample solution', intensity=123.4 }) {
  const el=ELEMENTS[element]; return <div className="fp-instrument" role="img" aria-label={`Flame photometer measuring ${el.name}`}>
    <div className="sample"><i/><span>{sample}</span></div><div className="capillary"/><div className="nebulizer"><span>Nebulizer</span></div><div className="burner"><span>Burner head</span></div>{lit&&<div className="flame"><i/><i/></div>}
    <div className="filter"><span style={{background:el.color}}/><b>{element}</b></div><div className="detector"><small>Intensity (a.u.)</small><strong>{intensity.toFixed(1)}</strong><em>{element}　λ = {el.wavelength.toFixed(1)} nm</em></div><div className="knobs"><i/><i/><span>Fuel (LPG)　　Air</span></div>
  </div>;
}
function SpectrumPlot({ element='Na', concentration=6, calibration=false }) {
  if(calibration){const fit=linearRegression(),u=unknownResult();return <svg className="fp-chart" viewBox="0 0 760 380" role="img" aria-label="Sodium calibration curve"><line x1="58" x2="715" y1="330" y2="330"/><line x1="58" x2="58" y1="25" y2="330"/><path d={`M58 ${330-fit.intercept} L${58+10*54} ${330-(fit.slope*10+fit.intercept)*1.15}`}/>{STANDARD_CONCENTRATIONS.map((x,i)=><circle key={x} cx={58+x*54} cy={330-SODIUM_INTENSITIES[i]*1.15} r="7"/>)}<line className="unknown" x1={58+u.diluted*54} x2={58+u.diluted*54} y1={330-u.intensity*1.15} y2="330"/><circle className="unknown-dot" cx={58+u.diluted*54} cy={330-u.intensity*1.15} r="9"/><text x="80" y="60">I = {fit.slope.toFixed(2)} C + {fit.intercept.toFixed(2)}</text><text x="80" y="88">R² = {fit.r2.toFixed(4)}</text><text x="260" y="372">Concentration (mg/L)</text></svg>}
  const values=Array.from({length:451},(_,i)=>{const w=400+i,y=spectrum(w,element,concentration);return `${45+(w-400)*1.45},${310-y*1.65}`}).join(' ');return <svg className="fp-chart spectrum" viewBox="0 0 760 360" role="img" aria-label={`${ELEMENTS[element].name} emission spectrum`}><line x1="45" x2="710" y1="310" y2="310"/><line x1="45" x2="45" y1="20" y2="310"/><polyline points={values}/>{Object.entries(ELEMENTS).map(([id,e])=><g key={id}><line className={id===element?'selected-line':''} x1={45+(e.wavelength-400)*1.45} x2={45+(e.wavelength-400)*1.45} y1="28" y2="310"/><text x={45+(e.wavelength-400)*1.45-12} y="45">{id}</text></g>)}<text x="275" y="348">Wavelength (nm)</text></svg>;
}
function FlameMap({fuel,air}){return <div className="fp-map"><span style={{left:`${(fuel-.2)/.8*85+5}%`,bottom:`${(air-2)/8*85+5}%`}}/><b>Optimal<br/>({fuel.toFixed(2)}, {air.toFixed(1)})</b></div>}

function Home({go}){return <main className="fp-home"><Panel title="Flame Photometry Laboratory" className="intro"><p className="kicker"><FlaskConical/> Atomic Emission Spectroscopy</p><p className="lead">Prepare standards. Optimize the flame. Determine alkali-metal concentration.</p><div className="fp-theory"><div><b>Beer–Lambert Type Relationship for Flame Emission</b><span>I = kC</span><small>Emission intensity is directly proportional to analyte concentration in the linear range.</small></div><SpectrumPlot calibration/></div><button className="primary" onClick={()=>go(1)}><FlaskConical/> Start Experiment <ChevronRight/></button></Panel><section className="fp-hero"><Instrument/><div className="fire"><Flame/> Fire extinguisher</div></section><div className="fp-cards">{['Instrument Setup','Emission Spectrum','Calibration Curve','Unknown Sample'].map((x,i)=><button key={x} onClick={()=>go(Math.min(5,i+2))}><Settings/><b>{x}</b><small>{['Set air and fuel for stability.','Compare Na, K, Li and Ca lines.','Measure standards and fit I vs. C.','Determine the diluted and original concentration.'][i]}</small><ChevronRight/></button>)}</div></main>}

function Standards({element,setElement,target,setTarget,added,setAdded}){const volume=dilutionVolume(target);return <main className="fp-three"><Panel title="Prepare Standards & Samples"><p className="kicker"><FlaskConical/> Atomic Emission Spectroscopy</p><h3>1. Select Analyte</h3><div className="fp-tabs">{Object.keys(ELEMENTS).map(id=><button className={element===id?'active':''} onClick={()=>setElement(id)} key={id}>{id}</button>)}</div><h3>2. Standard Preparation ({element})</h3><Metric label="Stock solution" value="1000 mg/L"/><Metric label="Final volume" value="100.0 mL"/><table><thead><tr><th>Standard</th><th>C₂ (mg/L)</th><th>V₁ (mL)</th></tr></thead><tbody>{STANDARD_CONCENTRATIONS.map((c,i)=><tr className={c===target?'active':''} onClick={()=>setTarget(c)} key={c}><td>S{i}</td><td>{c}</td><td>{dilutionVolume(c).toFixed(2)}</td></tr>)}</tbody></table></Panel><Panel title="Volumetric Preparation" className="fp-visual"><div className="fp-flasks">{STANDARD_CONCENTRATIONS.map((c,i)=><div className={c===target?'active':''} key={c}><i style={{'--fill':`${12+c*5}%`}}/><b>S{i}</b><small>{c} mg/L</small></div>)}</div><div className="pipette">Micropipette<br/><b>{(volume*1000).toFixed(0)} µL</b></div><p>Read the bottom of the meniscus at 100.0 mL.</p></Panel><Panel title="Calculation (C₁V₁ = C₂V₂)"><label>Target concentration <input aria-label="Target concentration" type="number" min="0" max="10" value={target} onChange={e=>setTarget(+e.target.value)}/> mg/L</label><Metric label="Stock C₁" value="1000 mg/L"/><Metric label="Final volume V₂" value="100 mL"/><div className="formula">C₁V₁ = C₂V₂<br/><small>V₁ = ({target} × 100) / 1000 = {volume.toFixed(3)} mL</small></div><p className="valid"><Check/> Calculation valid</p><h3>Preparation Checklist</h3>{['Stock labelled','Volumetric flasks labelled','Micropipette set','Stock added','Diluted to volume','Mixed by inversion'].map((x,i)=><p className="check" key={x}><input type="checkbox" checked={i<3||added} readOnly/>{x}</p>)}<button className="primary" onClick={()=>setAdded(true)}>+ Add Standard</button></Panel></main>}

function FlameScreen({fuel,setFuel,air,setAir,aspiration,setAspiration,height,setHeight,lit,setLit,saved,setSaved}){const perf=flamePerformance({fuel,air,aspiration,height});const auto=()=>{setFuel(.42);setAir(5);setAspiration(4.2);setHeight(10);setLit(true)};return <main className="fp-three"><Panel title="Ignite & Optimize Flame"><p>Set flame conditions and aspirate the blank solution.</p>{['Connect gases','Check leaks','Ignite flame','Adjust fuel/air','Aspirate blank'].map((x,i)=><p className={i===3?'step active':'step'} key={x}><b>{i+1}</b>{x}{i<3&&<Check/>}</p>)}<h3>Flame Controls</h3><label>LPG (fuel)<input aria-label="LPG fuel flow" type="number" min=".2" max="1" step=".01" value={fuel} onChange={e=>setFuel(+e.target.value)}/> L/min</label><label>Air (oxidant)<input aria-label="Air flow" type="number" min="2" max="10" step=".1" value={air} onChange={e=>setAir(+e.target.value)}/> L/min</label><label>Aspiration rate<input aria-label="Aspiration rate" type="number" min="1" max="10" step=".1" value={aspiration} onChange={e=>setAspiration(+e.target.value)}/> mL/min</label><label>Burner height<input aria-label="Burner height" type="number" min="5" max="20" value={height} onChange={e=>setHeight(+e.target.value)}/> mm</label></Panel><Panel title="Burner & Nebulizer" className="fp-visual"><Instrument lit={lit} intensity={perf.stability*1.5}/></Panel><Panel title="Flame Status"><Metric label="Flame stability" value={`${perf.stability.toFixed(1)}%`} good={perf.optimal}/><Metric label="Background intensity" value={`${perf.background.toFixed(1)} a.u.`}/><Metric label="Aspiration rate" value={`${aspiration.toFixed(1)} mL/min`}/><Metric label="Signal RSD" value={`${perf.rsd.toFixed(2)}%`}/><p className={perf.optimal&&lit?'valid':'notice'}>{perf.optimal&&lit?<><Check/> Optimal flame — stable and ready.</>:<>Adjust fuel and air, then ignite the flame.</>}</p><h3>Signal vs. Fuel/Air Ratio</h3><FlameMap fuel={fuel} air={air}/><div className="fp-actions"><button onClick={()=>setLit(true)}><Flame/> Ignite</button><button onClick={()=>setLit(false)}>■ Extinguish</button><button className="primary" onClick={auto}><Sparkles/> Auto-optimize</button></div><button onClick={()=>setSaved(true)}><Save/> {saved?'Conditions saved':'Save conditions'}</button></Panel></main>}

function SpectrumScreen({element,setElement,concentration,setConcentration,ran,setRan}){const el=ELEMENTS[element],peak=spectrum(el.wavelength,element,concentration);return <main className="fp-spectrum-layout"><Panel title="Emission Spectrum & Element Selection"><p>Select element, configure scan and acquire spectrum.</p>{Object.entries(ELEMENTS).map(([id,e])=><label className={element===id?'active':''} key={id}><input type="radio" checked={element===id} onChange={()=>setElement(id)}/><b>{id}</b>{e.name}<span>~ {e.wavelength.toFixed(1)} nm</span></label>)}<label>Sample concentration<input aria-label="Spectrum concentration" type="number" min="0" max="10" value={concentration} onChange={e=>setConcentration(+e.target.value)}/> mg/L</label><button className="primary" onClick={()=>setRan(true)}><Play/> Run spectrum</button></Panel><section className="fp-spectrum-center"><div className="fp-crop"><Instrument element={element} sample={`Sample S3 (${concentration} mg/L)`} intensity={peak}/></div><Panel title={`Emission Spectrum — ${ELEMENTS[element].name}`}><SpectrumPlot element={element} concentration={concentration}/><div className="spectrum-bar"/></Panel><Panel title="Process of Atomic Emission"><div className="emission-process">Nebulization　→　Desolvation　→　Atomization　→　Excitation　→　Photon emission</div></Panel></section><Panel title={`Peak Analysis (${el.name})`}><Metric label="Wavelength" value={`${el.wavelength.toFixed(1)} nm`}/><Metric label="Peak intensity" value={`${peak.toFixed(1)} a.u.`}/><Metric label="Background" value="1.8 a.u."/><Metric label="Corrected intensity" value={`${(peak-1.8).toFixed(1)} a.u.`}/><Metric label="Signal-to-noise" value={ran?'92':'—'}/><p className={ran?'valid':'notice'}>{ran?<><Check/> Optimal wavelength — strong, interference-free line.</>:<>Run the spectrum to verify the emission line.</>}</p><h3>Reference Lines</h3>{Object.entries(ELEMENTS).map(([id,e])=><Metric key={id} label={`${id} ${e.name}`} value={`${e.wavelength.toFixed(1)} nm`}/>)}</Panel></main>}

function Calibration({factor,setFactor,accepted,setAccepted}){const fit=linearRegression(),result=unknownResult(UNKNOWN_REPLICATES,factor);const csv=()=>download('flame-photometry-data.csv',['concentration,intensity',...STANDARD_CONCENTRATIONS.map((x,i)=>`${x},${SODIUM_INTENSITIES[i]}`)].join('\n'));return <main className="fp-cal"><Panel title="Calibration & Unknown Analysis"><h3>Standard Data (Sodium)</h3><table><thead><tr><th>mg/L</th><th>Corrected intensity</th><th>Include</th></tr></thead><tbody>{STANDARD_CONCENTRATIONS.map((c,i)=><tr key={c}><td>{c}</td><td>{SODIUM_INTENSITIES[i]}</td><td><input type="checkbox" checked readOnly/></td></tr>)}</tbody></table><h3>Unknown Sample (FP-12)</h3>{UNKNOWN_REPLICATES.map((x,i)=><Metric key={x} label={`Replicate ${i+1}`} value={x.toFixed(1)}/>) }<Metric label="Mean" value={result.intensity.toFixed(1)}/><Metric label="RSD" value={`${result.rsd.toFixed(2)}%`}/></Panel><Panel title="Calibration Curve — Sodium" className="fp-visual"><SpectrumPlot calibration/><p>Linear response from 0–10 mg/L. Signals above 10 mg/L may saturate.</p></Panel><Panel title="Unknown Result (FP-12)"><Metric label="Concentration (diluted)" value={`${result.diluted.toFixed(2)} ± 0.04 mg/L`} good/><label>Dilution factor<input aria-label="Dilution factor" type="number" min="1" max="100" value={factor} onChange={e=>setFactor(+e.target.value)}/></label><Metric label="Original concentration" value={`${result.original.toFixed(1)} ± 0.8 mg/L`} good/><div className="formula">C = (I − b) / m<br/><small>C = ({result.intensity.toFixed(1)} − {fit.intercept.toFixed(2)}) / {fit.slope.toFixed(2)}</small></div><h3>Quality Checks</h3>{['Within linear range','Replicate precision passes','Blank acceptable','Drift correction passes'].map(x=><p className="check" key={x}><Check/>{x}</p>)}<p className={accepted?'valid':'notice'}>{accepted?<><Check/> Result Accepted</>:<>Review quality checks before accepting.</>}</p><button className="primary" onClick={()=>setAccepted(true)}><Check/> Accept result</button><button onClick={csv}><Download/> Export data</button></Panel></main>}

function download(name,text){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function Report(){const[answers,setAnswers]=useState({}),score=[answers.q1==='atomize',answers.q2==='589',answers.q3==='proportional'].filter(Boolean).length,result=unknownResult(),fit=linearRegression();return <main className="fp-report"><Panel title="Flame Photometry Lab Report & Assessment"><div className="completion">100% Complete</div>{['Standards prepared','Flame optimized','Wavelength verified','Calibration validated','Unknown determined'].map(x=><p className="check" key={x}><Check/>{x}<span>100%</span></p>)}<Instrument intensity={result.intensity}/><Metric label="Elapsed time" value="24:36"/><Metric label="Safety compliance" value="100%" good/></Panel><Panel title="Digital Lab Notebook" className="wide"><div className="fp-tabs"><button className="active">Results</button><button>Spectrum</button><button>Calculations</button><button>Conclusion</button></div><table><tbody><tr><td>Analyte</td><td>Sodium (Na)</td></tr><tr><td>Analytical wavelength</td><td>589.0 nm</td></tr><tr><td>Calibration equation</td><td>I = {fit.slope.toFixed(2)} C + {fit.intercept.toFixed(2)}</td></tr><tr><td>Correlation coefficient</td><td>{fit.r2.toFixed(4)}</td></tr><tr><td>Diluted concentration</td><td>{result.diluted.toFixed(2)} ± 0.04 mg/L</td></tr><tr><td>Original concentration</td><td>{result.original.toFixed(1)} ± 0.8 mg/L</td></tr></tbody></table><div className="fp-report-charts"><SpectrumPlot/><SpectrumPlot calibration/></div><p className="valid"><Check/> The sodium concentration was determined reliably within the validated calibration range.</p></Panel><Panel title="Knowledge Check"><p>1. What is the purpose of the flame?</p><label><input type="radio" checked={answers.q1==='atomize'} onChange={()=>setAnswers(a=>({...a,q1:'atomize'}))}/> Atomize and excite analyte</label><p>2. What wavelength is used for sodium?</p><label><input type="radio" checked={answers.q2==='589'} onChange={()=>setAnswers(a=>({...a,q2:'589'}))}/> 589.0 nm</label><p>3. Within the linear range, intensity is:</p><label><input type="radio" checked={answers.q3==='proportional'} onChange={()=>setAnswers(a=>({...a,q3:'proportional'}))}/> Proportional to concentration</label><div className={score===3?'valid':'notice'}><Trophy/> Score: {score}/3</div><h3>Safety Confirmation</h3><p><ShieldCheck/> Flame extinguished and fuel isolated.</p><button onClick={()=>download('flame-photometry-report.csv','metric,value\noriginal concentration,100.0 mg/L')}><Download/> Download CSV</button><button onClick={()=>print()}><Download/> Export PDF</button></Panel></main>}

export default function FlamePhotometryLab(){const[step,setStep]=useState(initialStep),[element,setElement]=useState('Na'),[target,setTarget]=useState(6),[added,setAdded]=useState(false),[fuel,setFuel]=useState(.42),[air,setAir]=useState(5),[aspiration,setAspiration]=useState(4.2),[height,setHeight]=useState(10),[lit,setLit]=useState(false),[saved,setSaved]=useState(false),[concentration,setConcentration]=useState(6),[ran,setRan]=useState(false),[factor,setFactor]=useState(20),[accepted,setAccepted]=useState(false);const go=n=>{n=Math.max(0,Math.min(5,n));setStep(n);const u=new URL(location.href);u.searchParams.set('screen',STEPS[n][0]);history.replaceState({},'',u);scrollTo(0,0)};const reset=()=>{setElement('Na');setTarget(6);setAdded(false);setFuel(.42);setAir(5);setAspiration(4.2);setHeight(10);setLit(false);setSaved(false);setConcentration(6);setRan(false);setFactor(20);setAccepted(false);go(0)};return <div className="fp-app"><Header step={step} go={go} reset={reset}/>{step===0&&<Home go={go}/>} {step===1&&<Standards {...{element,setElement,target,setTarget,added,setAdded}}/>} {step===2&&<FlameScreen {...{fuel,setFuel,air,setAir,aspiration,setAspiration,height,setHeight,lit,setLit,saved,setSaved}}/>} {step===3&&<SpectrumScreen {...{element,setElement,concentration,setConcentration,ran,setRan}}/>} {step===4&&<Calibration {...{factor,setFactor,accepted,setAccepted}}/>} {step===5&&<Report/>}<Footer step={step} go={go}/></div>}
