import {useState,useId} from 'react';
import {absorbance} from './cobaltModel.js';

function Field({tetra=false}){
 const color=tetra?'#5eb7ff':'#f975c7';const levels=tetra?[[58,3,[1,1,1]],[132,2,[2,2]]]:[[58,2,[1,1]],[132,3,[2,2,1]]];
 return <div className="cobalt-field"><p style={{color}}>{tetra?'[CoCl₄]²⁻ · tetrahedral':'[Co(H₂O)₆]²⁺ · octahedral'}</p><svg viewBox="0 0 210 190" aria-label={tetra?'High-spin d7 tetrahedral: e4 t2 3':'High-spin d7 octahedral: t2g5 eg2'}><path d="M20 94H48L80 58M48 94L80 132" stroke="#7692ad" fill="none" strokeDasharray="4 3"/><text x="5" y="98" fill="#b4c6dc" fontSize="12">d⁷</text>{levels.map(([y,count,fill])=><g key={y}>{Array.from({length:count},(_,i)=>{const x=82+i*37;return <g key={i}><path d={`M${x} ${y}h29`} stroke="#d3e1ef"/><text x={x+2} y={y-7} fill={color} fontSize="28">{fill[i]===2?'↑↓':'↑'}</text></g>;})}<text x="20" y={y+4} fill="#c5d8e9" fontSize="14">{tetra?(count===3?'t₂':'e'):(count===2?'e_g':'t₂g')}</text></g>)}<path d="M197 64v61m-4-56 4-6 4 6m-8 51 4 6 4-6" stroke={color} fill="none"/><text x="120" y="175" textAnchor="middle" fill={color} fontSize="10">{tetra?'e⁴ t₂³':'t₂g⁵ e_g²'} · 3 unpaired</text></svg><small>Weak-field, high-spin d⁷<br/>{tetra?'Smaller Δₜ':'Octahedral Δₒ'} · schematic levels</small></div>;
}
export function CrystalField(){return <section className="cobalt-panel"><h3>Crystal-field splitting</h3><div className="cobalt-fields"><Field/><Field tetra/></div></section>;}
export function CobaltSpectrum({fraction}){
 const [compare,setCompare]=useState(true),[wave,setWave]=useState(null);const id=useId();
 const path=key=>Array.from({length:101},(_,i)=>{const w=400+i*4,a=absorbance(w,fraction);return `${i?'L':'M'}${40+i*2.7},${166-a[key]*140}`;}).join(' ');
 return <section className="cobalt-panel cobalt-spectrum"><h3>UV–Vis spectra <button aria-pressed={compare} onClick={()=>setCompare(v=>!v)}>Compare spectra</button></h3><svg viewBox="0 0 330 223" role="img" aria-label="Cobalt absorbance spectra, 400 to 800 nanometres" onPointerMove={e=>{const b=e.currentTarget.getBoundingClientRect();setWave(Math.max(400,Math.min(800,400+((e.clientX-b.left)/b.width*330-40)/270*400)));}} onPointerLeave={()=>setWave(null)}>{[0,.25,.5,.75,1].map(v=><g key={v}><path d={`M40 ${166-v*140}H310`} stroke="#243e54"/><text x="32" y={170-v*140} fill="#a7c0d9" fontSize="10" textAnchor="end">{v.toFixed(1)}</text></g>)}{[400,500,600,700,800].map((w,i)=><g key={w}><path d={`M${40+i*67.5} 26V166`} stroke="#243e54"/><text x={40+i*67.5} y="182" textAnchor="middle" fill="#aac3da" fontSize="10">{w}</text></g>)}{compare&&<><path d={path('pink')} stroke="#f76abb" fill="none" strokeWidth="2"/><path d={path('chloride')} stroke="#3c8fff" fill="none" strokeWidth="2"/></>}<path d={path('mixture')} stroke="#e9f8ff" fill="none" strokeWidth="2" strokeDasharray={compare?'4 3':undefined}/><text x="15" y="105" transform="rotate(-90 15 105)" textAnchor="middle" fill="#c2d7e8" fontSize="10">Absorbance (a.u.)</text><text x="176" y="199" textAnchor="middle" fill="#c2d7e8" fontSize="11">Wavelength (nm)</text><defs><linearGradient id={id}>{['#793dff','#003cff','#00dcff','#1bd53b','#f3ec28','#fa640c','#d41323'].map((c,i)=><stop key={c} offset={`${i/6*100}%`} stopColor={c}/>)}</linearGradient></defs><rect x="40" y="209" width="270" height="10" fill={`url(#${id})`}/></svg><div className="cobalt-spectrum-legend"><span>● Pink complex ≈510 nm</span><span>● Blue complex ≈685 nm</span><span>┄ Mixture</span></div><small>{wave?`${wave.toFixed(0)} nm · A = ${absorbance(wave,fraction).mixture.toFixed(3)}`:'Illustrative bands, not measured spectra. Blue → red: decreasing photon energy.'}</small></section>;
}
