const retrievedAt = "2026-09-09";

export const makeProvenance = ({
  database,
  id,
  url,
  kind = "experimental",
  method,
  notes,
}) => ({
  sourceDatabase: database,
  sourceId: id,
  sourceUrl: url,
  retrievedAt,
  experimentalOrPredicted: kind,
  method,
  notes,
});

export const COX2_TARGET = {
  id: "CHEMBL230",
  name: "Prostaglandin G/H synthase 2",
  commonName: "Cyclooxygenase-2 (COX-2)",
  gene: "PTGS2",
  uniprot: "P35354",
  organism: "Homo sapiens",
  function:
    "Converts arachidonic acid to prostaglandin H2 during prostanoid biosynthesis.",
  location: "Endoplasmic reticulum and nuclear envelope",
  provenance: [
    makeProvenance({
      database: "UniProt",
      id: "P35354",
      url: "https://www.uniprot.org/uniprotkb/P35354/entry",
      notes: "Human PTGS2 reviewed protein record",
    }),
    makeProvenance({
      database: "ChEMBL",
      id: "CHEMBL230",
      url: "https://www.ebi.ac.uk/chembl/explore/target/CHEMBL230",
      notes: "Human single-protein target",
    }),
  ],
};

export const COX2_STRUCTURE = {
  id: "5IKR",
  title: "Human COX-2 bound to mefenamic acid",
  ligand: "Mefenamic acid",
  ligandCode: "ID8",
  method: "X-ray diffraction",
  resolution: 2.342,
  organism: "Homo sapiens",
  chains: ["A", "B"],
  source: "/assets/drug-discovery/structures/5IKR.cif",
  ligandSource: "/assets/drug-discovery/structures/ID8_ideal.sdf",
  residues: ["His90", "Arg120", "Tyr385", "Ser530"],
  provenance: makeProvenance({
    database: "RCSB PDB",
    id: "5IKR",
    url: "https://www.rcsb.org/structure/5IKR",
    method: "X-ray diffraction, 2.342 Å",
    notes: "Deposited complex; ID8 is mefenamic acid in chains A and B",
  }),
};

const pubchem = (cid) => `https://pubchem.ncbi.nlm.nih.gov/compound/${cid}`;
const chembl = (id) => `https://www.ebi.ac.uk/chembl/explore/compound/${id}`;
const compound = (data) => ({
  ...data,
  image: `/assets/drug-discovery/compounds/${data.slug}.png`,
  sdf: `/assets/drug-discovery/compounds/${data.slug}.sdf`,
  provenance: [
    makeProvenance({
      database: "PubChem",
      id: `CID ${data.cid}`,
      url: pubchem(data.cid),
      kind: "computed",
      method: "PubChem Standardization Service and conformer record",
      notes: "Identity, formula, descriptors, 2D depiction and 3D conformer",
    }),
    makeProvenance({
      database: "ChEMBL",
      id: data.chembl,
      url: chembl(data.chembl),
      notes: "Compound identity and human COX-2 activity record",
    }),
  ],
});

export const COMPOUNDS = [
  compound({
    slug: "celecoxib",
    name: "Celecoxib",
    cid: 2662,
    chembl: "CHEMBL118",
    formula: "C17H14F3N3O2S",
    mw: 381.4,
    smiles: "CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(=O)(=O)N)C(F)(F)F",
    inchikey: "RZEKVGVHFLEQIL-UHFFFAOYSA-N",
    logp: 3.4,
    tpsa: 86.4,
    hbd: 1,
    hba: 7,
    rotatable: 3,
    heavy: 26,
  }),
  compound({
    slug: "rofecoxib",
    name: "Rofecoxib",
    cid: 5090,
    chembl: "CHEMBL122",
    formula: "C17H14O4S",
    mw: 314.4,
    smiles: "CS(=O)(=O)C1=CC=C(C=C1)C2=C(C(=O)OC2)C3=CC=CC=C3",
    inchikey: "RZJQGNCSTQAWON-UHFFFAOYSA-N",
    logp: 2.3,
    tpsa: 68.8,
    hbd: 0,
    hba: 4,
    rotatable: 3,
    heavy: 22,
  }),
  compound({
    slug: "valdecoxib",
    name: "Valdecoxib",
    cid: 119607,
    chembl: "CHEMBL865",
    formula: "C16H14N2O3S",
    mw: 314.4,
    smiles: "CC1=C(C(=NO1)C2=CC=CC=C2)C3=CC=C(C=C3)S(=O)(=O)N",
    inchikey: "LNPDTQAFDNKSHK-UHFFFAOYSA-N",
    logp: 2.6,
    tpsa: 94.6,
    hbd: 1,
    hba: 5,
    rotatable: 3,
    heavy: 22,
  }),
  compound({
    slug: "etoricoxib",
    name: "Etoricoxib",
    cid: 123619,
    chembl: "CHEMBL416146",
    formula: "C18H15ClN2O2S",
    mw: 358.8,
    smiles: "CC1=NC=C(C=C1)C2=C(C=C(C=N2)Cl)C3=CC=C(C=C3)S(=O)(=O)C",
    inchikey: "MNJVRJDLRVPLFE-UHFFFAOYSA-N",
    logp: 3.3,
    tpsa: 68.3,
    hbd: 0,
    hba: 4,
    rotatable: 3,
    heavy: 24,
  }),
  compound({
    slug: "mefenamic-acid",
    name: "Mefenamic acid",
    cid: 4044,
    chembl: "CHEMBL686",
    formula: "C15H15NO2",
    mw: 241.28,
    smiles: "CC1=C(C(=CC=C1)NC2=CC=CC=C2C(=O)O)C",
    inchikey: "HYYBABOKPJLUIN-UHFFFAOYSA-N",
    logp: 5.1,
    tpsa: 49.3,
    hbd: 2,
    hba: 3,
    rotatable: 3,
    heavy: 18,
  }),
  compound({
    slug: "meloxicam",
    name: "Meloxicam",
    cid: 54677470,
    chembl: "CHEMBL599",
    formula: "C14H13N3O4S2",
    mw: 351.4,
    smiles: "CC1=CN=C(S1)NC(=O)C2=C(C3=CC=CC=C3S(=O)(=O)N2C)O",
    inchikey: "ZRVUJXDFFKFLMG-UHFFFAOYSA-N",
    logp: 3.0,
    tpsa: 136,
    hbd: 2,
    hba: 7,
    rotatable: 2,
    heavy: 23,
  }),
  compound({
    slug: "diclofenac",
    name: "Diclofenac",
    cid: 3033,
    chembl: "CHEMBL139",
    formula: "C14H11Cl2NO2",
    mw: 296.1,
    smiles: "C1=CC=C(C(=C1)CC(=O)O)NC2=C(C=CC=C2Cl)Cl",
    inchikey: "DCOPUUMXTXDBNB-UHFFFAOYSA-N",
    logp: 4.4,
    tpsa: 49.3,
    hbd: 2,
    hba: 3,
    rotatable: 4,
    heavy: 19,
  }),
  compound({
    slug: "ibuprofen",
    name: "Ibuprofen",
    cid: 3672,
    chembl: "CHEMBL521",
    formula: "C13H18O2",
    mw: 206.28,
    smiles: "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O",
    inchikey: "HEFNNWSXXWATRW-UHFFFAOYSA-N",
    logp: 3.5,
    tpsa: 37.3,
    hbd: 1,
    hba: 2,
    rotatable: 4,
    heavy: 15,
  }),
];

export const DESIGNED_ANALOG = compound({
  slug: "meclofenamic-acid",
  name: "Meclofenamic acid",
  cid: 4037,
  chembl: "CHEMBL509",
  formula: "C14H11Cl2NO2",
  mw: 296.1,
  smiles: "CC1=C(C(=C(C=C1)Cl)NC2=CC=CC=C2C(=O)O)Cl",
  inchikey: "SBDNJUWAMKYJOX-UHFFFAOYSA-N",
  logp: 5.0,
  tpsa: 49.3,
  hbd: 2,
  hba: 3,
  rotatable: 3,
  heavy: 19,
});

const activity = (
  compoundName,
  moleculeId,
  value,
  pchembl,
  assayId,
  documentId,
) => ({
  target: "CHEMBL230 · human PTGS2",
  compound: compoundName,
  moleculeId,
  assayId,
  activityType: "IC50",
  standardValue: value,
  unit: "nM",
  relation: "=",
  organism: "Homo sapiens",
  confidenceScore: 9,
  dataValidityComment: "No ChEMBL data-validity flag",
  reference: documentId,
  pchembl,
  provenance: makeProvenance({
    database: "ChEMBL",
    id: assayId,
    url: `https://www.ebi.ac.uk/chembl/explore/assay/${assayId}`,
    method: "Single-protein IC50 record",
    notes: `Document ${documentId}; values are not assumed comparable across assay formats.`,
  }),
});

export const ACTIVITIES = [
  activity(
    "Celecoxib",
    "CHEMBL118",
    120,
    6.92,
    "CHEMBL766726",
    "CHEMBL1136052",
  ),
  activity(
    "Rofecoxib",
    "CHEMBL122",
    530,
    6.28,
    "CHEMBL769652",
    "CHEMBL1147594",
  ),
  activity(
    "Valdecoxib",
    "CHEMBL865",
    5.012,
    8.3,
    "CHEMBL763870",
    "CHEMBL1134614",
  ),
  activity(
    "Etoricoxib",
    "CHEMBL416146",
    810,
    6.09,
    "CHEMBL766724",
    "CHEMBL1149180",
  ),
  activity(
    "Mefenamic acid",
    "CHEMBL686",
    602,
    6.22,
    "CHEMBL1909131",
    "CHEMBL1909046",
  ),
  activity("Meloxicam", "CHEMBL599", 160, 6.8, "CHEMBL763341", "CHEMBL1130988"),
  activity("Diclofenac", "CHEMBL139", 50, 7.3, "CHEMBL763081", "CHEMBL1131765"),
  activity(
    "Ibuprofen",
    "CHEMBL521",
    30000,
    4.52,
    "CHEMBL765812",
    "CHEMBL1131303",
  ),
];

export const ROUTES = [
  ["home", "Home"],
  ["workspace", "Drug Discovery"],
  ["targets", "Targets"],
  ["screening", "Screening"],
  ["design", "Molecular Design"],
  ["adme", "ADME & PK"],
  ["safety", "Safety & Toxicity"],
  ["analytics", "Data & Analytics"],
  ["notebooks", "Notebooks"],
  ["team", "Team"],
];

export const SCREENING_STEPS = [
  "Select target",
  "Prepare receptor",
  "Define pocket",
  "Load library",
  "Property filters",
  "Generate conformers",
  "Dock / load poses",
  "Rescore",
  "Inspect poses",
  "Select hits",
];

export const SEARCH_INDEX = [
  {
    type: "Target",
    title: "Prostaglandin G/H synthase 2",
    detail: "PTGS2 · CHEMBL230 · P35354",
    route: "targets",
    source: "UniProt / ChEMBL",
  },
  {
    type: "Structure",
    title: "5IKR",
    detail: "COX-2 · mefenamic acid (ID8)",
    route: "workspace",
    source: "RCSB PDB",
  },
  ...COMPOUNDS.map((c) => ({
    type: "Compound",
    title: c.name,
    detail: `CID ${c.cid} · ${c.chembl} · ${c.inchikey}`,
    route: "workspace",
    source: "PubChem / ChEMBL",
  })),
  ...ACTIVITIES.map((a) => ({
    type: "Assay",
    title: a.assayId,
    detail: `${a.compound} ${a.activityType} ${a.standardValue} ${a.unit}`,
    route: "analytics",
    source: "ChEMBL",
  })),
  {
    type: "Notebook",
    title: "COX-2 evidence review",
    detail: "5IKR structure and CHEMBL230 activity series",
    route: "notebooks",
    source: "Project notebook",
  },
];

export const ALL_PROVENANCE = [
  COX2_STRUCTURE.provenance,
  ...COX2_TARGET.provenance,
  ...COMPOUNDS.flatMap((c) => c.provenance),
  ...ACTIVITIES.map((a) => a.provenance),
];
