import { ArrowRight, Check, Bookmark } from 'lucide-react';
import { discoveryEntries, findExperience, learningPaths } from '../../data/discoveryCatalog.js';
import { useLocalStorage } from '../../hooks/useLocalStorage.js';
export default function LearningHub({recentPages=[],favorites=[],onLaunch,onBrowse}) {
  const [tab,setTab]=useLocalStorage('cu-learning-hub-tab','Start here');
  const [profile,setProfile]=useLocalStorage('cu-learning-profile',{level:'Beginner',interest:'elements'});
  const [completed,setCompleted]=useLocalStorage('cu-discovery-completed',[]);
  const [activePath,setActivePath]=useLocalStorage('cu-active-learning-path','foundations');
  const [symmetry]=useLocalStorage('cu-molecular-symmetry-progress',{score:0,attempts:0});
  const path=learningPaths.find(item=>item.id===activePath)||learningPaths[0];
  const recommendation=learningPaths.find(item=>item.interest===profile.interest&&item.level===profile.level)||learningPaths.find(item=>item.interest===profile.interest)||learningPaths.find(item=>item.level===profile.level)||learningPaths[0];
  const recent=[...new Set(recentPages)].map(findExperience).filter(Boolean).slice(0,4);
  const newest=[...discoveryEntries].filter(entry=>entry.addedAt&&!entry.upcoming).sort((a,b)=>b.addedAt.localeCompare(a.addedAt)).slice(0,4);
  return <section className="dx-learning-hub" aria-labelledby="dx-learning-title"><div className="cl-section-heading"><div><span className="cl-eyebrow">A PATH THAT FITS YOU</span><h2 id="dx-learning-title">Keep your curiosity moving.</h2></div></div>
    <div className="dx-tabs" aria-label="Learning collections">{['Start here','Learning paths','Continue learning','Recently added','Saved'].map(name=><button key={name} aria-pressed={tab===name} onClick={()=>setTab(name)}>{name}</button>)}</div>
    {tab==='Start here'&&<div className="dx-onboarding"><div><h3>Find your starting point</h3><p>Choose an interest and study level. You can change them any time.</p><label>Study level<select value={profile.level} onChange={event=>setProfile({...profile,level:event.target.value})}>{['Beginner','Intermediate','Advanced'].map(level=><option key={level}>{level}</option>)}</select></label><label>I'm interested in<select value={profile.interest} onChange={event=>setProfile({...profile,interest:event.target.value})}><option value="elements">Atoms & elements</option><option value="organic">Reactions</option><option value="analytical">Analysis & experiments</option><option value="biochemistry">Chemistry of life</option><option value="pharma">Research & drug discovery</option></select></label></div><div className="dx-path-pick"><span className="cl-eyebrow">SUGGESTED PATH · {recommendation.level.toUpperCase()}</span><h3>{recommendation.title}</h3><p>{recommendation.description}</p><button className="dx-primary" onClick={()=>{setActivePath(recommendation.id);setTab('Learning paths');}}>Explore this path <ArrowRight size={17}/></button></div></div>}
    {tab==='Learning paths'&&<div className="dx-paths"><label>Choose a path<select value={activePath} onChange={event=>setActivePath(event.target.value)}>{learningPaths.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><p>{path.description}</p><progress max={path.steps.length} value={path.steps.filter(id=>completed.includes(id)).length}/><span>{path.steps.filter(id=>completed.includes(id)).length} of {path.steps.length} marked complete</span><ol>{path.steps.map((id,index)=>{const entry=findExperience(id);return entry&&<li key={id}><span className="dx-step">{completed.includes(id)?<Check size={17}/>:index+1}</span><button onClick={()=>onLaunch(entry)}><strong>{entry.title}</strong><small>{entry.objective}</small></button><label><input type="checkbox" checked={completed.includes(id)} onChange={()=>setCompleted(previous=>previous.includes(id)?previous.filter(value=>value!==id):[...previous,id])}/> Complete</label></li>;})}</ol><p className="dx-note">Progress reflects the steps you mark complete on this device.</p></div>}
    {tab==='Continue learning'&&<><p>Return to your recent activities. Each experience keeps its own saved state when supported.</p><div className="dx-compact-grid">{recent.map(entry=><button key={entry.id} onClick={()=>onLaunch(entry)}><small>RECENTLY VISITED</small><strong>{entry.title}</strong><span>{completed.includes(entry.id)?'Marked complete':'Open again'} <ArrowRight size={15}/></span></button>)}</div>{!recent.length&&<p>No activities visited yet. Open an experience to start your history.</p>}{symmetry.attempts>0&&<p>Symmetry practice: {symmetry.score} correct across {symmetry.attempts} saved attempts.</p>}</>}
    {tab==='Recently added'&&<><p>Latest additions to the catalog, dated from project history.</p><div className="dx-compact-grid">{newest.map(entry=><button key={entry.id} onClick={()=>onLaunch(entry)}><time dateTime={entry.addedAt}>{entry.addedAt}</time><strong>{entry.title}</strong><span>Explore <ArrowRight size={15}/></span></button>)}</div></>}
    {tab==='Saved'&&<><p>{favorites.length?`${favorites.filter(id=>findExperience(id)).length} catalog experiences saved on this device.`:'Save an experience using the bookmark on its card.'}</p><div className="dx-compact-grid">{favorites.map(findExperience).filter(Boolean).slice(0,4).map(entry=><button key={entry.id} onClick={()=>!entry.upcoming&&onLaunch(entry)} disabled={entry.upcoming}><Bookmark size={16}/><strong>{entry.title}</strong><span>{entry.upcoming?'Upcoming':'Open saved experience'}</span></button>)}</div><button className="cl-text-button" onClick={()=>onBrowse()}>Browse saved experiences <ArrowRight size={16}/></button></>}
  </section>;
}
